/**
 * Add more colleges - Batch 2
 * State flagships and popular universities
 */

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const newColleges = [
  // More State Flagships
  {
    name: "University of Oregon",
    slug: "university-of-oregon",
    location: "Eugene, OR",
    setting: "Urban",
    institutionalSector: "Public",
    undergraduateEnrollment: 18528,
    studentsAdmittedPercent: 88,
    costOfAttendanceInState: 33442,
    costOfAttendanceOutOfState: 56298,
    studentFacultyRatio: "17:1",
    admissionsSelectivity: "Less Selective",
    testPolicy: "Test Optional",
    retentionRate: 85,
    graduationRate4yr: 56,
    graduationRate6yr: 74,
    medianEarnings10yr: 52000,
    website: "https://www.uoregon.edu",
    description: "The University of Oregon is a public research university in Eugene, Oregon. Known for its journalism, business, law, and science programs. Home of the Ducks and the Knight Campus for Accelerating Scientific Impact.",
    popularMajors: JSON.stringify(["Business", "Psychology", "Journalism", "Biology", "Computer Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 560, max: 670 }, math: { min: 540, max: 660 }, total: { min: 1100, max: 1330 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 22, max: 28 }, percentSubmitted: 25 }),
    totalApplicants: 27456,
    totalAdmitted: 24161,
    totalEnrolled: 4200,
    yieldRate: 17.4,
    rdDeadline: "January 15",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 22000,
    genderDistribution: JSON.stringify({ women: 55, men: 45 }),
    raceEthnicity: JSON.stringify({ White: 58, Asian: 8, Hispanic: 14, Black: 2, "Two or More Races": 8, International: 8, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "State residency": "Considered"
    }),
    primaryColor: "#154733",
    secondaryColor: "#FEE123"
  },
  {
    name: "University of Kentucky",
    slug: "university-of-kentucky",
    location: "Lexington, KY",
    setting: "Urban",
    institutionalSector: "Public",
    undergraduateEnrollment: 22227,
    studentsAdmittedPercent: 90,
    costOfAttendanceInState: 32426,
    costOfAttendanceOutOfState: 51428,
    studentFacultyRatio: "15:1",
    admissionsSelectivity: "Less Selective",
    testPolicy: "Test Optional",
    retentionRate: 85,
    graduationRate4yr: 48,
    graduationRate6yr: 67,
    medianEarnings10yr: 50000,
    website: "https://www.uky.edu",
    description: "The University of Kentucky is a public research university in Lexington. It is the flagship university of the Commonwealth of Kentucky, known for its pharmacy, engineering, and agriculture programs.",
    popularMajors: JSON.stringify(["Marketing", "Finance", "Biology", "Psychology", "Nursing"]),
    satScores: JSON.stringify({ readingWriting: { min: 540, max: 650 }, math: { min: 530, max: 650 }, total: { min: 1070, max: 1300 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 22, max: 28 }, percentSubmitted: 55 }),
    totalApplicants: 21456,
    totalAdmitted: 19310,
    totalEnrolled: 5100,
    yieldRate: 26.4,
    rdDeadline: "February 15",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 18000,
    genderDistribution: JSON.stringify({ women: 55, men: 45 }),
    raceEthnicity: JSON.stringify({ White: 78, Asian: 4, Hispanic: 5, Black: 6, "Two or More Races": 4, International: 2, Unknown: 1 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Important",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "State residency": "Considered"
    }),
    primaryColor: "#0033A0",
    secondaryColor: "#FFFFFF"
  },
  {
    name: "University of Oklahoma",
    slug: "university-of-oklahoma",
    location: "Norman, OK",
    setting: "Suburban",
    institutionalSector: "Public",
    undergraduateEnrollment: 22628,
    studentsAdmittedPercent: 83,
    costOfAttendanceInState: 28652,
    costOfAttendanceOutOfState: 48852,
    studentFacultyRatio: "18:1",
    admissionsSelectivity: "Less Selective",
    testPolicy: "Test Required",
    retentionRate: 87,
    graduationRate4yr: 42,
    graduationRate6yr: 70,
    medianEarnings10yr: 52000,
    website: "https://www.ou.edu",
    description: "The University of Oklahoma is a public research university in Norman. Known for its petroleum engineering, meteorology, and dance programs. Home to the Sooners with strong athletic traditions.",
    popularMajors: JSON.stringify(["Engineering", "Business", "Health Sciences", "Journalism", "Psychology"]),
    satScores: JSON.stringify({ readingWriting: { min: 560, max: 670 }, math: { min: 550, max: 670 }, total: { min: 1110, max: 1340 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 60 }),
    totalApplicants: 18234,
    totalAdmitted: 15134,
    totalEnrolled: 4800,
    yieldRate: 31.7,
    rdDeadline: "February 1",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 19000,
    genderDistribution: JSON.stringify({ women: 50, men: 50 }),
    raceEthnicity: JSON.stringify({ White: 58, Asian: 5, Hispanic: 12, Black: 5, "American Indian": 6, "Two or More Races": 8, International: 4, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Very Important",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "State residency": "Considered"
    }),
    primaryColor: "#841617",
    secondaryColor: "#FDF9D8"
  },
  {
    name: "University of South Carolina",
    slug: "university-of-south-carolina",
    location: "Columbia, SC",
    setting: "Urban",
    institutionalSector: "Public",
    undergraduateEnrollment: 27523,
    studentsAdmittedPercent: 63,
    costOfAttendanceInState: 28528,
    costOfAttendanceOutOfState: 52106,
    studentFacultyRatio: "18:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 88,
    graduationRate4yr: 59,
    graduationRate6yr: 77,
    medianEarnings10yr: 50000,
    website: "https://www.sc.edu",
    description: "The University of South Carolina is a public research university in Columbia. Known for its international business program, ranked #1 nationally, and strong programs in hospitality and nursing.",
    popularMajors: JSON.stringify(["Business", "Biology", "Psychology", "Exercise Science", "Nursing"]),
    satScores: JSON.stringify({ readingWriting: { min: 590, max: 680 }, math: { min: 580, max: 680 }, total: { min: 1170, max: 1360 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 24, max: 30 }, percentSubmitted: 35 }),
    totalApplicants: 42567,
    totalAdmitted: 26817,
    totalEnrolled: 6200,
    yieldRate: 23.1,
    rdDeadline: "December 1",
    eaDeadline: "October 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 20000,
    genderDistribution: JSON.stringify({ women: 55, men: 45 }),
    raceEthnicity: JSON.stringify({ White: 70, Asian: 3, Hispanic: 7, Black: 10, "Two or More Races": 4, International: 4, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "State residency": "Important"
    }),
    primaryColor: "#73000A",
    secondaryColor: "#000000"
  },
  {
    name: "University of Kansas",
    slug: "university-of-kansas",
    location: "Lawrence, KS",
    setting: "Urban",
    institutionalSector: "Public",
    undergraduateEnrollment: 19052,
    studentsAdmittedPercent: 88,
    costOfAttendanceInState: 28100,
    costOfAttendanceOutOfState: 47350,
    studentFacultyRatio: "17:1",
    admissionsSelectivity: "Less Selective",
    testPolicy: "Test Optional",
    retentionRate: 83,
    graduationRate4yr: 45,
    graduationRate6yr: 65,
    medianEarnings10yr: 52000,
    website: "https://www.ku.edu",
    description: "The University of Kansas is a public research university in Lawrence. Known for its pharmacy, journalism, and special education programs. Rock Chalk Jayhawk!",
    popularMajors: JSON.stringify(["Business", "Psychology", "Biology", "Journalism", "Engineering"]),
    satScores: JSON.stringify({ readingWriting: { min: 540, max: 660 }, math: { min: 530, max: 660 }, total: { min: 1070, max: 1320 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 22, max: 28 }, percentSubmitted: 55 }),
    totalApplicants: 15678,
    totalAdmitted: 13796,
    totalEnrolled: 4100,
    yieldRate: 29.7,
    rdDeadline: "February 1",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 17000,
    genderDistribution: JSON.stringify({ women: 50, men: 50 }),
    raceEthnicity: JSON.stringify({ White: 68, Asian: 4, Hispanic: 10, Black: 5, "Two or More Races": 6, International: 5, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "State residency": "Considered"
    }),
    primaryColor: "#0051BA",
    secondaryColor: "#E8000D"
  },
  {
    name: "University of Missouri",
    slug: "university-of-missouri",
    location: "Columbia, MO",
    setting: "Suburban",
    institutionalSector: "Public",
    undergraduateEnrollment: 23556,
    studentsAdmittedPercent: 82,
    costOfAttendanceInState: 29364,
    costOfAttendanceOutOfState: 47918,
    studentFacultyRatio: "17:1",
    admissionsSelectivity: "Less Selective",
    testPolicy: "Test Optional",
    retentionRate: 85,
    graduationRate4yr: 47,
    graduationRate6yr: 70,
    medianEarnings10yr: 50000,
    website: "https://missouri.edu",
    description: "The University of Missouri is a public research university in Columbia. Known for its journalism school (the first in the world) and strong programs in health sciences and agriculture.",
    popularMajors: JSON.stringify(["Business", "Health Sciences", "Journalism", "Engineering", "Psychology"]),
    satScores: JSON.stringify({ readingWriting: { min: 550, max: 660 }, math: { min: 540, max: 660 }, total: { min: 1090, max: 1320 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 55 }),
    totalApplicants: 18234,
    totalAdmitted: 14952,
    totalEnrolled: 5200,
    yieldRate: 34.8,
    rdDeadline: "May 1",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 18000,
    genderDistribution: JSON.stringify({ women: 52, men: 48 }),
    raceEthnicity: JSON.stringify({ White: 72, Asian: 3, Hispanic: 5, Black: 8, "Two or More Races": 5, International: 5, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "State residency": "Considered"
    }),
    primaryColor: "#F1B82D",
    secondaryColor: "#000000"
  },
  {
    name: "University of Iowa",
    slug: "university-of-iowa",
    location: "Iowa City, IA",
    setting: "Urban",
    institutionalSector: "Public",
    undergraduateEnrollment: 21973,
    studentsAdmittedPercent: 84,
    costOfAttendanceInState: 26142,
    costOfAttendanceOutOfState: 49816,
    studentFacultyRatio: "15:1",
    admissionsSelectivity: "Less Selective",
    testPolicy: "Test Optional",
    retentionRate: 87,
    graduationRate4yr: 57,
    graduationRate6yr: 74,
    medianEarnings10yr: 53000,
    website: "https://uiowa.edu",
    description: "The University of Iowa is a public research university in Iowa City. Known for its writing programs (Iowa Writers' Workshop), healthcare, and performing arts. Member of the Big Ten.",
    popularMajors: JSON.stringify(["Business", "Engineering", "Psychology", "Communication Studies", "Nursing"]),
    satScores: JSON.stringify({ readingWriting: { min: 560, max: 670 }, math: { min: 560, max: 680 }, total: { min: 1120, max: 1350 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 55 }),
    totalApplicants: 24567,
    totalAdmitted: 20636,
    totalEnrolled: 4800,
    yieldRate: 23.3,
    rdDeadline: "May 1",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 18000,
    genderDistribution: JSON.stringify({ women: 52, men: 48 }),
    raceEthnicity: JSON.stringify({ White: 68, Asian: 4, Hispanic: 8, Black: 4, "Two or More Races": 4, International: 10, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "State residency": "Considered"
    }),
    primaryColor: "#FFCD00",
    secondaryColor: "#000000"
  },
  // More selective private universities
  {
    name: "University of Rochester",
    slug: "university-of-rochester",
    location: "Rochester, NY",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 6780,
    studentsAdmittedPercent: 39,
    costOfAttendanceInState: 81820,
    costOfAttendanceOutOfState: 81820,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 93,
    graduationRate4yr: 78,
    graduationRate6yr: 88,
    medianEarnings10yr: 68000,
    website: "https://www.rochester.edu",
    description: "The University of Rochester is a private research university in Rochester, New York. Known for its music school (Eastman), optics program, and flexible 'Rochester Curriculum' without required courses.",
    popularMajors: JSON.stringify(["Biology", "Psychology", "Economics", "Computer Science", "Political Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 680, max: 750 }, math: { min: 710, max: 790 }, total: { min: 1390, max: 1540 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 32, max: 35 }, percentSubmitted: 30 }),
    totalApplicants: 22567,
    totalAdmitted: 8801,
    totalEnrolled: 1350,
    yieldRate: 15.3,
    rdDeadline: "January 5",
    edDeadline: "November 1",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 35000,
    genderDistribution: JSON.stringify({ women: 50, men: 50 }),
    raceEthnicity: JSON.stringify({ White: 38, Asian: 18, Hispanic: 9, Black: 6, "Two or More Races": 5, International: 22, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Very Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Important",
      "Interview": "Important"
    }),
    primaryColor: "#003B71",
    secondaryColor: "#FFD100"
  },
  {
    name: "Lehigh University",
    slug: "lehigh-university",
    location: "Bethlehem, PA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 5624,
    studentsAdmittedPercent: 37,
    costOfAttendanceInState: 80680,
    costOfAttendanceOutOfState: 80680,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 94,
    graduationRate4yr: 83,
    graduationRate6yr: 90,
    medianEarnings10yr: 82000,
    website: "https://www.lehigh.edu",
    description: "Lehigh University is a private research university in Bethlehem, Pennsylvania. Known for its engineering, business, and integrated degree programs combining liberal arts with technical fields.",
    popularMajors: JSON.stringify(["Finance", "Mechanical Engineering", "Accounting", "Computer Science", "Marketing"]),
    satScores: JSON.stringify({ readingWriting: { min: 670, max: 740 }, math: { min: 700, max: 780 }, total: { min: 1370, max: 1520 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 31, max: 34 }, percentSubmitted: 30 }),
    totalApplicants: 17234,
    totalAdmitted: 6377,
    totalEnrolled: 1280,
    yieldRate: 20.1,
    rdDeadline: "January 1",
    edDeadline: "November 1",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 45, men: 55 }),
    raceEthnicity: JSON.stringify({ White: 55, Asian: 12, Hispanic: 9, Black: 4, "Two or More Races": 4, International: 14, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#502D0E",
    secondaryColor: "#FFFFFF"
  },
  {
    name: "Rensselaer Polytechnic Institute",
    slug: "rensselaer-polytechnic-institute",
    location: "Troy, NY",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 6366,
    studentsAdmittedPercent: 57,
    costOfAttendanceInState: 79448,
    costOfAttendanceOutOfState: 79448,
    studentFacultyRatio: "13:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 93,
    graduationRate4yr: 69,
    graduationRate6yr: 86,
    medianEarnings10yr: 92000,
    website: "https://www.rpi.edu",
    description: "Rensselaer Polytechnic Institute is a private research university in Troy, New York. Founded in 1824, it is one of the oldest technological universities in the English-speaking world.",
    popularMajors: JSON.stringify(["Computer Science", "Mechanical Engineering", "Electrical Engineering", "Business", "Information Technology"]),
    satScores: JSON.stringify({ readingWriting: { min: 660, max: 740 }, math: { min: 710, max: 790 }, total: { min: 1370, max: 1530 }, percentSubmitted: 50 }),
    actScores: JSON.stringify({ composite: { min: 30, max: 34 }, percentSubmitted: 30 }),
    totalApplicants: 22345,
    totalAdmitted: 12737,
    totalEnrolled: 1650,
    yieldRate: 13,
    rdDeadline: "January 15",
    edDeadline: "November 1",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 40000,
    genderDistribution: JSON.stringify({ women: 35, men: 65 }),
    raceEthnicity: JSON.stringify({ White: 48, Asian: 18, Hispanic: 8, Black: 4, "Two or More Races": 4, International: 16, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#D6001C",
    secondaryColor: "#000000"
  },
  {
    name: "Stevens Institute of Technology",
    slug: "stevens-institute-of-technology",
    location: "Hoboken, NJ",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 4067,
    studentsAdmittedPercent: 51,
    costOfAttendanceInState: 78478,
    costOfAttendanceOutOfState: 78478,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 93,
    graduationRate4yr: 56,
    graduationRate6yr: 84,
    medianEarnings10yr: 98000,
    website: "https://www.stevens.edu",
    description: "Stevens Institute of Technology is a private research university in Hoboken, New Jersey. Known for its engineering and technology programs, with stunning views of the Manhattan skyline.",
    popularMajors: JSON.stringify(["Mechanical Engineering", "Computer Science", "Computer Engineering", "Business", "Chemical Engineering"]),
    satScores: JSON.stringify({ readingWriting: { min: 660, max: 730 }, math: { min: 710, max: 780 }, total: { min: 1370, max: 1510 }, percentSubmitted: 50 }),
    actScores: JSON.stringify({ composite: { min: 31, max: 34 }, percentSubmitted: 25 }),
    totalApplicants: 13456,
    totalAdmitted: 6863,
    totalEnrolled: 1050,
    yieldRate: 15.3,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 42000,
    genderDistribution: JSON.stringify({ women: 32, men: 68 }),
    raceEthnicity: JSON.stringify({ White: 38, Asian: 25, Hispanic: 12, Black: 4, "Two or More Races": 4, International: 15, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#A32638",
    secondaryColor: "#666666"
  },
  {
    name: "Worcester Polytechnic Institute",
    slug: "worcester-polytechnic-institute",
    location: "Worcester, MA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 5028,
    studentsAdmittedPercent: 55,
    costOfAttendanceInState: 75956,
    costOfAttendanceOutOfState: 75956,
    studentFacultyRatio: "13:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 94,
    graduationRate4yr: 68,
    graduationRate6yr: 87,
    medianEarnings10yr: 88000,
    website: "https://www.wpi.edu",
    description: "Worcester Polytechnic Institute is a private research university in Worcester, Massachusetts. Known for its project-based curriculum and global projects program with centers around the world.",
    popularMajors: JSON.stringify(["Mechanical Engineering", "Computer Science", "Electrical Engineering", "Biomedical Engineering", "Aerospace Engineering"]),
    satScores: JSON.stringify({ readingWriting: { min: 650, max: 730 }, math: { min: 700, max: 780 }, total: { min: 1350, max: 1510 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 30, max: 34 }, percentSubmitted: 25 }),
    totalApplicants: 12678,
    totalAdmitted: 6973,
    totalEnrolled: 1250,
    yieldRate: 17.9,
    rdDeadline: "February 1",
    eaDeadline: "November 1",
    edDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 38, men: 62 }),
    raceEthnicity: JSON.stringify({ White: 50, Asian: 12, Hispanic: 8, Black: 3, "Two or More Races": 4, International: 21, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#AC2B37",
    secondaryColor: "#A7A9AC"
  },
  {
    name: "Santa Clara University",
    slug: "santa-clara-university",
    location: "Santa Clara, CA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 5932,
    studentsAdmittedPercent: 49,
    costOfAttendanceInState: 80817,
    costOfAttendanceOutOfState: 80817,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 94,
    graduationRate4yr: 82,
    graduationRate6yr: 91,
    medianEarnings10yr: 82000,
    website: "https://www.scu.edu",
    description: "Santa Clara University is a private Jesuit university in Santa Clara, California. Located in Silicon Valley, it's known for its business and engineering programs with strong tech industry connections.",
    popularMajors: JSON.stringify(["Finance", "Computer Science", "Accounting", "Marketing", "Communication"]),
    satScores: JSON.stringify({ readingWriting: { min: 650, max: 730 }, math: { min: 670, max: 770 }, total: { min: 1320, max: 1500 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 30, max: 34 }, percentSubmitted: 25 }),
    totalApplicants: 17234,
    totalAdmitted: 8445,
    totalEnrolled: 1400,
    yieldRate: 16.6,
    rdDeadline: "January 7",
    eaDeadline: "November 1",
    edDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 42000,
    genderDistribution: JSON.stringify({ women: 52, men: 48 }),
    raceEthnicity: JSON.stringify({ White: 35, Asian: 25, Hispanic: 20, Black: 3, "Two or More Races": 8, International: 7, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#862633",
    secondaryColor: "#B5985A"
  },
  {
    name: "Loyola Marymount University",
    slug: "loyola-marymount-university",
    location: "Los Angeles, CA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 7054,
    studentsAdmittedPercent: 46,
    costOfAttendanceInState: 77400,
    costOfAttendanceOutOfState: 77400,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 90,
    graduationRate4yr: 76,
    graduationRate6yr: 84,
    medianEarnings10yr: 65000,
    website: "https://www.lmu.edu",
    description: "Loyola Marymount University is a private Jesuit university in Los Angeles. Known for its film and television production program and beautiful bluff-top campus overlooking the Pacific Ocean.",
    popularMajors: JSON.stringify(["Business", "Film/Television Production", "Psychology", "Communication Studies", "Biology"]),
    satScores: JSON.stringify({ readingWriting: { min: 620, max: 710 }, math: { min: 610, max: 710 }, total: { min: 1230, max: 1420 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 27, max: 32 }, percentSubmitted: 25 }),
    totalApplicants: 20456,
    totalAdmitted: 9410,
    totalEnrolled: 1650,
    yieldRate: 17.5,
    rdDeadline: "January 15",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 42000,
    genderDistribution: JSON.stringify({ women: 57, men: 43 }),
    raceEthnicity: JSON.stringify({ White: 38, Asian: 12, Hispanic: 25, Black: 5, "Two or More Races": 8, International: 9, Unknown: 3 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#00416B",
    secondaryColor: "#982F41"
  },
  {
    name: "Pepperdine University",
    slug: "pepperdine-university",
    location: "Malibu, CA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 3627,
    studentsAdmittedPercent: 42,
    costOfAttendanceInState: 80820,
    costOfAttendanceOutOfState: 80820,
    studentFacultyRatio: "13:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 92,
    graduationRate4yr: 78,
    graduationRate6yr: 86,
    medianEarnings10yr: 65000,
    website: "https://www.pepperdine.edu",
    description: "Pepperdine University is a private Christian university in Malibu, California. Known for its stunning coastal campus and strong programs in business, law, and public policy.",
    popularMajors: JSON.stringify(["Business Administration", "Communication", "Psychology", "Sports Medicine", "International Studies"]),
    satScores: JSON.stringify({ readingWriting: { min: 620, max: 710 }, math: { min: 610, max: 720 }, total: { min: 1230, max: 1430 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 27, max: 32 }, percentSubmitted: 30 }),
    totalApplicants: 14567,
    totalAdmitted: 6118,
    totalEnrolled: 850,
    yieldRate: 13.9,
    rdDeadline: "January 15",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 45000,
    genderDistribution: JSON.stringify({ women: 60, men: 40 }),
    raceEthnicity: JSON.stringify({ White: 45, Asian: 12, Hispanic: 15, Black: 5, "Two or More Races": 8, International: 12, Unknown: 3 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#0033A0",
    secondaryColor: "#FF6900"
  },
];

async function main() {
  console.log("Adding batch 2 colleges to database...\n");

  let added = 0;
  let updated = 0;

  for (const college of newColleges) {
    const existing = await db.college.findUnique({
      where: { slug: college.slug },
    });

    if (existing) {
      await db.college.update({
        where: { slug: college.slug },
        data: college,
      });
      console.log(`Updated: ${college.name}`);
      updated++;
    } else {
      await db.college.create({
        data: college,
      });
      console.log(`Added: ${college.name}`);
      added++;
    }
  }

  console.log(`\n✓ Added ${added} new colleges`);
  console.log(`✓ Updated ${updated} existing colleges`);

  const total = await db.college.count();
  console.log(`\nTotal colleges in database: ${total}`);

  await db.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
