/**
 * Add more notable colleges to the database
 * Data sourced from Common Data Set 2023-2024, IPEDS, and institutional websites
 */

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

interface CollegeData {
  name: string;
  slug: string;
  location: string;
  setting: string;
  institutionalSector: string;
  undergraduateEnrollment: number;
  studentsAdmittedPercent: number;
  costOfAttendanceInState: number;
  costOfAttendanceOutOfState: number;
  studentFacultyRatio: string;
  admissionsSelectivity: string;
  testPolicy: string;
  retentionRate: number;
  graduationRate4yr: number;
  graduationRate6yr: number;
  medianEarnings10yr: number;
  website: string;
  description: string;
  popularMajors: string;
  satScores: string;
  actScores: string;
  totalApplicants: number;
  totalAdmitted: number;
  totalEnrolled: number;
  yieldRate: number;
  rdDeadline: string;
  eaDeadline?: string;
  edDeadline?: string;
  earlyActionType?: string;
  fafsaRequired: boolean;
  cssProfileRequired: boolean;
  averageNetPrice: number;
  genderDistribution: string;
  raceEthnicity: string;
  admissionConsiderations: string;
  primaryColor: string;
  secondaryColor?: string;
}

const newColleges: CollegeData[] = [
  // Notable Liberal Arts Colleges
  {
    name: "Brandeis University",
    slug: "brandeis-university",
    location: "Waltham, MA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 3688,
    studentsAdmittedPercent: 34,
    costOfAttendanceInState: 82878,
    costOfAttendanceOutOfState: 82878,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 91,
    graduationRate4yr: 83,
    graduationRate6yr: 89,
    medianEarnings10yr: 72000,
    website: "https://www.brandeis.edu",
    description: "Brandeis University is a private research university in Waltham, Massachusetts. Founded in 1948, it is the only nonsectarian Jewish-sponsored college or university in the country. Known for its strong programs in the sciences, social sciences, and humanities.",
    popularMajors: JSON.stringify(["Biology", "Economics", "Psychology", "Computer Science", "Business"]),
    satScores: JSON.stringify({ readingWriting: { min: 680, max: 750 }, math: { min: 700, max: 780 }, total: { min: 1380, max: 1530 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 31, max: 34 }, percentSubmitted: 25 }),
    totalApplicants: 12894,
    totalAdmitted: 4384,
    totalEnrolled: 885,
    yieldRate: 20.2,
    rdDeadline: "January 15",
    edDeadline: "November 1",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 32000,
    genderDistribution: JSON.stringify({ women: 59, men: 41 }),
    raceEthnicity: JSON.stringify({ White: 42, Asian: 15, Hispanic: 10, Black: 5, "Two or More Races": 5, International: 20, Unknown: 3 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#003478"
  },
  {
    name: "Connecticut College",
    slug: "connecticut-college",
    location: "New London, CT",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 1828,
    studentsAdmittedPercent: 38,
    costOfAttendanceInState: 78810,
    costOfAttendanceOutOfState: 78810,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 89,
    graduationRate4yr: 80,
    graduationRate6yr: 84,
    medianEarnings10yr: 62000,
    website: "https://www.conncoll.edu",
    description: "Connecticut College is a private liberal arts college in New London, Connecticut. Founded in 1911, it offers a distinctive curriculum combining academic study with career development and global engagement.",
    popularMajors: JSON.stringify(["Economics", "Psychology", "Political Science", "Biology", "English"]),
    satScores: JSON.stringify({ readingWriting: { min: 650, max: 720 }, math: { min: 640, max: 730 }, total: { min: 1290, max: 1450 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 29, max: 32 }, percentSubmitted: 20 }),
    totalApplicants: 7854,
    totalAdmitted: 2985,
    totalEnrolled: 492,
    yieldRate: 16.5,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 35000,
    genderDistribution: JSON.stringify({ women: 60, men: 40 }),
    raceEthnicity: JSON.stringify({ White: 58, Asian: 5, Hispanic: 10, Black: 4, "Two or More Races": 5, International: 12, Unknown: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#002B5C"
  },
  {
    name: "Trinity College",
    slug: "trinity-college",
    location: "Hartford, CT",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2167,
    studentsAdmittedPercent: 33,
    costOfAttendanceInState: 79480,
    costOfAttendanceOutOfState: 79480,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 89,
    graduationRate4yr: 79,
    graduationRate6yr: 84,
    medianEarnings10yr: 72000,
    website: "https://www.trincoll.edu",
    description: "Trinity College is a private liberal arts college in Hartford, Connecticut. Founded in 1823, it is the second-oldest college in Connecticut. Known for its Gothic architecture and strong programs in the liberal arts and sciences.",
    popularMajors: JSON.stringify(["Economics", "Political Science", "Psychology", "English", "Neuroscience"]),
    satScores: JSON.stringify({ readingWriting: { min: 640, max: 720 }, math: { min: 640, max: 740 }, total: { min: 1280, max: 1460 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 28, max: 32 }, percentSubmitted: 25 }),
    totalApplicants: 7245,
    totalAdmitted: 2391,
    totalEnrolled: 550,
    yieldRate: 23,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 36000,
    genderDistribution: JSON.stringify({ women: 50, men: 50 }),
    raceEthnicity: JSON.stringify({ White: 55, Asian: 5, Hispanic: 12, Black: 6, "Two or More Races": 4, International: 13, Unknown: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Important"
    }),
    primaryColor: "#002868"
  },
  {
    name: "Union College",
    slug: "union-college",
    location: "Schenectady, NY",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2100,
    studentsAdmittedPercent: 42,
    costOfAttendanceInState: 78558,
    costOfAttendanceOutOfState: 78558,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 92,
    graduationRate4yr: 82,
    graduationRate6yr: 87,
    medianEarnings10yr: 75000,
    website: "https://www.union.edu",
    description: "Union College is a private liberal arts college in Schenectady, New York. Founded in 1795, it was the first college chartered by the New York State Board of Regents. Known for its strong engineering program integrated with liberal arts.",
    popularMajors: JSON.stringify(["Economics", "Political Science", "Psychology", "Mechanical Engineering", "Biology"]),
    satScores: JSON.stringify({ readingWriting: { min: 630, max: 710 }, math: { min: 650, max: 750 }, total: { min: 1280, max: 1460 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 28, max: 32 }, percentSubmitted: 25 }),
    totalApplicants: 8432,
    totalAdmitted: 3541,
    totalEnrolled: 560,
    yieldRate: 15.8,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 48, men: 52 }),
    raceEthnicity: JSON.stringify({ White: 62, Asian: 7, Hispanic: 9, Black: 4, "Two or More Races": 4, International: 9, Unknown: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Important"
    }),
    primaryColor: "#862633"
  },
  {
    name: "Skidmore College",
    slug: "skidmore-college",
    location: "Saratoga Springs, NY",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2700,
    studentsAdmittedPercent: 32,
    costOfAttendanceInState: 78792,
    costOfAttendanceOutOfState: 78792,
    studentFacultyRatio: "8:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 90,
    graduationRate4yr: 82,
    graduationRate6yr: 86,
    medianEarnings10yr: 58000,
    website: "https://www.skidmore.edu",
    description: "Skidmore College is a private liberal arts college in Saratoga Springs, New York. Known for its creative thought matters approach and strong programs in the arts, sciences, and social sciences.",
    popularMajors: JSON.stringify(["Business", "Psychology", "English", "Political Science", "Biology"]),
    satScores: JSON.stringify({ readingWriting: { min: 640, max: 720 }, math: { min: 620, max: 720 }, total: { min: 1260, max: 1440 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 28, max: 32 }, percentSubmitted: 20 }),
    totalApplicants: 11789,
    totalAdmitted: 3772,
    totalEnrolled: 680,
    yieldRate: 18,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 35000,
    genderDistribution: JSON.stringify({ women: 62, men: 38 }),
    raceEthnicity: JSON.stringify({ White: 58, Asian: 6, Hispanic: 11, Black: 4, "Two or More Races": 5, International: 11, Unknown: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#006747"
  },
  {
    name: "Colorado College",
    slug: "colorado-college",
    location: "Colorado Springs, CO",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2197,
    studentsAdmittedPercent: 11,
    costOfAttendanceInState: 79556,
    costOfAttendanceOutOfState: 79556,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Most Selective",
    testPolicy: "Test Optional",
    retentionRate: 94,
    graduationRate4yr: 84,
    graduationRate6yr: 89,
    medianEarnings10yr: 58000,
    website: "https://www.coloradocollege.edu",
    description: "Colorado College is a private liberal arts college in Colorado Springs, Colorado. Known for its distinctive Block Plan, where students take one course at a time for 3.5 weeks, allowing for deep immersion in subjects.",
    popularMajors: JSON.stringify(["Economics", "Biology", "Political Science", "English", "Environmental Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 680, max: 750 }, math: { min: 680, max: 770 }, total: { min: 1360, max: 1520 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 31, max: 34 }, percentSubmitted: 35 }),
    totalApplicants: 14589,
    totalAdmitted: 1605,
    totalEnrolled: 540,
    yieldRate: 33.6,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 32000,
    genderDistribution: JSON.stringify({ women: 55, men: 45 }),
    raceEthnicity: JSON.stringify({ White: 58, Asian: 5, Hispanic: 13, Black: 2, "Two or More Races": 7, International: 8, Unknown: 7 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Important",
      "Interview": "Considered"
    }),
    primaryColor: "#CFB87C"
  },
  {
    name: "Rollins College",
    slug: "rollins-college",
    location: "Winter Park, FL",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2072,
    studentsAdmittedPercent: 57,
    costOfAttendanceInState: 70540,
    costOfAttendanceOutOfState: 70540,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 85,
    graduationRate4yr: 68,
    graduationRate6yr: 74,
    medianEarnings10yr: 56000,
    website: "https://www.rollins.edu",
    description: "Rollins College is a private liberal arts college in Winter Park, Florida. Founded in 1885, it is the oldest recognized college in Florida. Known for its lakeside campus and strong programs in business and the arts.",
    popularMajors: JSON.stringify(["Business Administration", "Economics", "Psychology", "Communication Studies", "International Business"]),
    satScores: JSON.stringify({ readingWriting: { min: 590, max: 680 }, math: { min: 570, max: 670 }, total: { min: 1160, max: 1350 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 25, max: 30 }, percentSubmitted: 20 }),
    totalApplicants: 5234,
    totalAdmitted: 2983,
    totalEnrolled: 485,
    yieldRate: 16.3,
    rdDeadline: "February 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 58, men: 42 }),
    raceEthnicity: JSON.stringify({ White: 55, Asian: 3, Hispanic: 20, Black: 5, "Two or More Races": 4, International: 10, Unknown: 3 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#002F6C"
  },
  {
    name: "Elon University",
    slug: "elon-university",
    location: "Elon, NC",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 6291,
    studentsAdmittedPercent: 72,
    costOfAttendanceInState: 57621,
    costOfAttendanceOutOfState: 57621,
    studentFacultyRatio: "12:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 90,
    graduationRate4yr: 80,
    graduationRate6yr: 84,
    medianEarnings10yr: 58000,
    website: "https://www.elon.edu",
    description: "Elon University is a private university in Elon, North Carolina. Known for its engaged learning approach combining academics with experiential learning, including study abroad, internships, and undergraduate research.",
    popularMajors: JSON.stringify(["Business Administration", "Communications", "Psychology", "Exercise Science", "Finance"]),
    satScores: JSON.stringify({ readingWriting: { min: 600, max: 680 }, math: { min: 580, max: 670 }, total: { min: 1180, max: 1350 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 25, max: 30 }, percentSubmitted: 25 }),
    totalApplicants: 17892,
    totalAdmitted: 12882,
    totalEnrolled: 1650,
    yieldRate: 12.8,
    rdDeadline: "January 10",
    edDeadline: "November 1",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 34000,
    genderDistribution: JSON.stringify({ women: 60, men: 40 }),
    raceEthnicity: JSON.stringify({ White: 76, Asian: 3, Hispanic: 7, Black: 5, "Two or More Races": 4, International: 3, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#6F263D"
  },
  {
    name: "Chapman University",
    slug: "chapman-university",
    location: "Orange, CA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 7626,
    studentsAdmittedPercent: 56,
    costOfAttendanceInState: 78844,
    costOfAttendanceOutOfState: 78844,
    studentFacultyRatio: "13:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 90,
    graduationRate4yr: 72,
    graduationRate6yr: 82,
    medianEarnings10yr: 62000,
    website: "https://www.chapman.edu",
    description: "Chapman University is a private university in Orange, California. Known for its strong film school (Dodge College of Film and Media Arts) and programs in business, sciences, and the performing arts.",
    popularMajors: JSON.stringify(["Business Administration", "Film/Television Production", "Psychology", "Communication Studies", "Biology"]),
    satScores: JSON.stringify({ readingWriting: { min: 620, max: 710 }, math: { min: 600, max: 700 }, total: { min: 1220, max: 1410 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 27, max: 31 }, percentSubmitted: 25 }),
    totalApplicants: 16543,
    totalAdmitted: 9264,
    totalEnrolled: 1750,
    yieldRate: 18.9,
    rdDeadline: "January 15",
    edDeadline: "November 1",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 42000,
    genderDistribution: JSON.stringify({ women: 62, men: 38 }),
    raceEthnicity: JSON.stringify({ White: 46, Asian: 12, Hispanic: 18, Black: 3, "Two or More Races": 8, International: 8, Unknown: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#A50034"
  },
  // HBCU
  {
    name: "Xavier University of Louisiana",
    slug: "xavier-university-of-louisiana",
    location: "New Orleans, LA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2473,
    studentsAdmittedPercent: 63,
    costOfAttendanceInState: 38798,
    costOfAttendanceOutOfState: 38798,
    studentFacultyRatio: "13:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 74,
    graduationRate4yr: 36,
    graduationRate6yr: 52,
    medianEarnings10yr: 55000,
    website: "https://www.xula.edu",
    description: "Xavier University of Louisiana is a private, historically Black, Roman Catholic university in New Orleans. It is the only Catholic HBCU and the nation's top producer of African American students who go on to complete medical school.",
    popularMajors: JSON.stringify(["Biology", "Psychology", "Chemistry", "Pharmacy", "Pre-Medicine"]),
    satScores: JSON.stringify({ readingWriting: { min: 510, max: 610 }, math: { min: 500, max: 600 }, total: { min: 1010, max: 1210 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 20, max: 25 }, percentSubmitted: 50 }),
    totalApplicants: 7234,
    totalAdmitted: 4557,
    totalEnrolled: 650,
    yieldRate: 14.3,
    rdDeadline: "March 1",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 22000,
    genderDistribution: JSON.stringify({ women: 73, men: 27 }),
    raceEthnicity: JSON.stringify({ Black: 76, Asian: 10, Hispanic: 4, White: 2, "Two or More Races": 3, International: 4, Unknown: 1 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Important",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#00563F"
  },
  // Art & Design Schools
  {
    name: "School of the Art Institute of Chicago",
    slug: "school-of-the-art-institute-of-chicago",
    location: "Chicago, IL",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2483,
    studentsAdmittedPercent: 58,
    costOfAttendanceInState: 68500,
    costOfAttendanceOutOfState: 68500,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Free",
    retentionRate: 83,
    graduationRate4yr: 55,
    graduationRate6yr: 65,
    medianEarnings10yr: 36000,
    website: "https://www.saic.edu",
    description: "The School of the Art Institute of Chicago is a private art school in Chicago. It is one of the largest accredited independent art and design schools in the United States, connected to the Art Institute of Chicago museum.",
    popularMajors: JSON.stringify(["Fine Arts", "Photography", "Film/Animation", "Painting", "Fashion Design"]),
    satScores: JSON.stringify({ readingWriting: { min: 580, max: 700 }, math: { min: 530, max: 650 }, total: { min: 1110, max: 1350 }, percentSubmitted: 10 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 5 }),
    totalApplicants: 4156,
    totalAdmitted: 2410,
    totalEnrolled: 420,
    yieldRate: 17.4,
    rdDeadline: "February 1",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 45000,
    genderDistribution: JSON.stringify({ women: 68, men: 32 }),
    raceEthnicity: JSON.stringify({ White: 38, Asian: 15, Hispanic: 12, Black: 5, "Two or More Races": 6, International: 20, Unknown: 4 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Important",
      "Academic GPA": "Important",
      "Standardized test scores": "Not Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Very Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#231F20"
  },
  {
    name: "California College of the Arts",
    slug: "california-college-of-the-arts",
    location: "San Francisco, CA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 1345,
    studentsAdmittedPercent: 79,
    costOfAttendanceInState: 67924,
    costOfAttendanceOutOfState: 67924,
    studentFacultyRatio: "8:1",
    admissionsSelectivity: "Less Selective",
    testPolicy: "Test Free",
    retentionRate: 78,
    graduationRate4yr: 48,
    graduationRate6yr: 58,
    medianEarnings10yr: 40000,
    website: "https://www.cca.edu",
    description: "California College of the Arts is a private art and design college with campuses in San Francisco and Oakland. Known for its programs in architecture, design, fine arts, and writing.",
    popularMajors: JSON.stringify(["Graphic Design", "Illustration", "Architecture", "Industrial Design", "Fashion Design"]),
    satScores: JSON.stringify({ readingWriting: { min: 540, max: 660 }, math: { min: 500, max: 620 }, total: { min: 1040, max: 1280 }, percentSubmitted: 8 }),
    actScores: JSON.stringify({ composite: { min: 21, max: 27 }, percentSubmitted: 4 }),
    totalApplicants: 2456,
    totalAdmitted: 1940,
    totalEnrolled: 280,
    yieldRate: 14.4,
    rdDeadline: "February 1",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 42000,
    genderDistribution: JSON.stringify({ women: 65, men: 35 }),
    raceEthnicity: JSON.stringify({ White: 28, Asian: 22, Hispanic: 15, Black: 3, "Two or More Races": 8, International: 20, Unknown: 4 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Important",
      "Academic GPA": "Important",
      "Standardized test scores": "Not Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Very Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#000000"
  },
  {
    name: "School of Visual Arts",
    slug: "school-of-visual-arts",
    location: "New York, NY",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 3652,
    studentsAdmittedPercent: 68,
    costOfAttendanceInState: 65500,
    costOfAttendanceOutOfState: 65500,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Free",
    retentionRate: 82,
    graduationRate4yr: 52,
    graduationRate6yr: 63,
    medianEarnings10yr: 42000,
    website: "https://www.sva.edu",
    description: "School of Visual Arts is a private art and design college in Manhattan, New York City. It is one of the largest and most influential independent colleges of art and design in the United States.",
    popularMajors: JSON.stringify(["Illustration", "Graphic Design", "Film/Video", "Computer Art", "Photography"]),
    satScores: JSON.stringify({ readingWriting: { min: 540, max: 650 }, math: { min: 510, max: 620 }, total: { min: 1050, max: 1270 }, percentSubmitted: 10 }),
    actScores: JSON.stringify({ composite: { min: 21, max: 27 }, percentSubmitted: 5 }),
    totalApplicants: 5234,
    totalAdmitted: 3559,
    totalEnrolled: 750,
    yieldRate: 21.1,
    rdDeadline: "February 1",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 45000,
    genderDistribution: JSON.stringify({ women: 62, men: 38 }),
    raceEthnicity: JSON.stringify({ White: 32, Asian: 18, Hispanic: 15, Black: 5, "Two or More Races": 6, International: 20, Unknown: 4 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Important",
      "Academic GPA": "Important",
      "Standardized test scores": "Not Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Very Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#000000"
  },
  {
    name: "Maryland Institute College of Art",
    slug: "maryland-institute-college-of-art",
    location: "Baltimore, MD",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 1687,
    studentsAdmittedPercent: 64,
    costOfAttendanceInState: 67520,
    costOfAttendanceOutOfState: 67520,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Free",
    retentionRate: 84,
    graduationRate4yr: 58,
    graduationRate6yr: 68,
    medianEarnings10yr: 38000,
    website: "https://www.mica.edu",
    description: "Maryland Institute College of Art (MICA) is a private art and design college in Baltimore. It is one of the oldest continuously degree-granting colleges of art in the nation, founded in 1826.",
    popularMajors: JSON.stringify(["Illustration", "Graphic Design", "Painting", "Animation", "Photography"]),
    satScores: JSON.stringify({ readingWriting: { min: 570, max: 680 }, math: { min: 530, max: 640 }, total: { min: 1100, max: 1320 }, percentSubmitted: 10 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 5 }),
    totalApplicants: 3567,
    totalAdmitted: 2283,
    totalEnrolled: 390,
    yieldRate: 17.1,
    rdDeadline: "February 1",
    edDeadline: "November 15",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 40000,
    genderDistribution: JSON.stringify({ women: 68, men: 32 }),
    raceEthnicity: JSON.stringify({ White: 42, Asian: 12, Hispanic: 10, Black: 8, "Two or More Races": 6, International: 18, Unknown: 4 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Important",
      "Academic GPA": "Important",
      "Standardized test scores": "Not Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Very Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#000000"
  },
  {
    name: "Otis College of Art and Design",
    slug: "otis-college-of-art-and-design",
    location: "Los Angeles, CA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 1156,
    studentsAdmittedPercent: 82,
    costOfAttendanceInState: 64856,
    costOfAttendanceOutOfState: 64856,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Less Selective",
    testPolicy: "Test Free",
    retentionRate: 76,
    graduationRate4yr: 45,
    graduationRate6yr: 56,
    medianEarnings10yr: 42000,
    website: "https://www.otis.edu",
    description: "Otis College of Art and Design is a private art and design college in Los Angeles. Known for its programs in fashion design, toy design, product design, and digital media.",
    popularMajors: JSON.stringify(["Fashion Design", "Illustration", "Graphic Design", "Product Design", "Game/Entertainment Design"]),
    satScores: JSON.stringify({ readingWriting: { min: 520, max: 640 }, math: { min: 490, max: 600 }, total: { min: 1010, max: 1240 }, percentSubmitted: 8 }),
    actScores: JSON.stringify({ composite: { min: 20, max: 26 }, percentSubmitted: 4 }),
    totalApplicants: 1856,
    totalAdmitted: 1522,
    totalEnrolled: 250,
    yieldRate: 16.4,
    rdDeadline: "February 15",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 40000,
    genderDistribution: JSON.stringify({ women: 70, men: 30 }),
    raceEthnicity: JSON.stringify({ White: 20, Asian: 25, Hispanic: 30, Black: 4, "Two or More Races": 6, International: 12, Unknown: 3 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Considered",
      "Academic GPA": "Important",
      "Standardized test scores": "Not Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Very Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#000000"
  },
  // Music Conservatories
  {
    name: "Manhattan School of Music",
    slug: "manhattan-school-of-music",
    location: "New York, NY",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 425,
    studentsAdmittedPercent: 40,
    costOfAttendanceInState: 73500,
    costOfAttendanceOutOfState: 73500,
    studentFacultyRatio: "6:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Free",
    retentionRate: 87,
    graduationRate4yr: 65,
    graduationRate6yr: 72,
    medianEarnings10yr: 35000,
    website: "https://www.msmnyc.edu",
    description: "Manhattan School of Music is a private music conservatory in New York City. Founded in 1917, it offers undergraduate and graduate programs in classical music, jazz, and musical theatre.",
    popularMajors: JSON.stringify(["Classical Performance", "Jazz Studies", "Composition", "Musical Theatre", "Orchestral Performance"]),
    satScores: JSON.stringify({ readingWriting: { min: 550, max: 680 }, math: { min: 520, max: 650 }, total: { min: 1070, max: 1330 }, percentSubmitted: 5 }),
    actScores: JSON.stringify({ composite: { min: 22, max: 28 }, percentSubmitted: 3 }),
    totalApplicants: 1256,
    totalAdmitted: 502,
    totalEnrolled: 105,
    yieldRate: 20.9,
    rdDeadline: "December 1",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 42000,
    genderDistribution: JSON.stringify({ women: 48, men: 52 }),
    raceEthnicity: JSON.stringify({ White: 35, Asian: 25, Hispanic: 8, Black: 5, "Two or More Races": 4, International: 20, Unknown: 3 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Considered",
      "Academic GPA": "Considered",
      "Standardized test scores": "Not Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Very Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Very Important"
    }),
    primaryColor: "#003366"
  },
  {
    name: "San Francisco Conservatory of Music",
    slug: "san-francisco-conservatory-of-music",
    location: "San Francisco, CA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 175,
    studentsAdmittedPercent: 38,
    costOfAttendanceInState: 69500,
    costOfAttendanceOutOfState: 69500,
    studentFacultyRatio: "5:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Free",
    retentionRate: 85,
    graduationRate4yr: 60,
    graduationRate6yr: 68,
    medianEarnings10yr: 32000,
    website: "https://sfcm.edu",
    description: "The San Francisco Conservatory of Music is a private music conservatory in San Francisco. It is one of the leading conservatories in the western United States, offering rigorous training in classical music.",
    popularMajors: JSON.stringify(["Classical Performance", "Composition", "Chamber Music", "Orchestral Studies", "Voice"]),
    satScores: JSON.stringify({ readingWriting: { min: 560, max: 680 }, math: { min: 530, max: 650 }, total: { min: 1090, max: 1330 }, percentSubmitted: 5 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 3 }),
    totalApplicants: 534,
    totalAdmitted: 203,
    totalEnrolled: 45,
    yieldRate: 22.2,
    rdDeadline: "December 1",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 52, men: 48 }),
    raceEthnicity: JSON.stringify({ White: 30, Asian: 35, Hispanic: 8, Black: 3, "Two or More Races": 4, International: 18, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Considered",
      "Academic GPA": "Considered",
      "Standardized test scores": "Not Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Very Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Very Important"
    }),
    primaryColor: "#003057"
  },
  {
    name: "Peabody Institute",
    slug: "peabody-institute",
    location: "Baltimore, MD",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 320,
    studentsAdmittedPercent: 35,
    costOfAttendanceInState: 71500,
    costOfAttendanceOutOfState: 71500,
    studentFacultyRatio: "5:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Free",
    retentionRate: 88,
    graduationRate4yr: 62,
    graduationRate6yr: 72,
    medianEarnings10yr: 35000,
    website: "https://peabody.jhu.edu",
    description: "The Peabody Institute of The Johns Hopkins University is a music conservatory in Baltimore. Founded in 1857, it is the oldest conservatory in the United States and offers world-class training in classical music.",
    popularMajors: JSON.stringify(["Classical Performance", "Composition", "Recording Arts", "Music Education", "Jazz Performance"]),
    satScores: JSON.stringify({ readingWriting: { min: 600, max: 720 }, math: { min: 580, max: 700 }, total: { min: 1180, max: 1420 }, percentSubmitted: 10 }),
    actScores: JSON.stringify({ composite: { min: 25, max: 31 }, percentSubmitted: 5 }),
    totalApplicants: 987,
    totalAdmitted: 345,
    totalEnrolled: 82,
    yieldRate: 23.8,
    rdDeadline: "December 1",
    edDeadline: "November 1",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 35000,
    genderDistribution: JSON.stringify({ women: 50, men: 50 }),
    raceEthnicity: JSON.stringify({ White: 38, Asian: 28, Hispanic: 8, Black: 5, "Two or More Races": 5, International: 14, Unknown: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Considered",
      "Academic GPA": "Considered",
      "Standardized test scores": "Not Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Very Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Very Important"
    }),
    primaryColor: "#002D72"
  },
];

async function main() {
  console.log("Adding new colleges to database...\n");

  let added = 0;
  let updated = 0;

  for (const college of newColleges) {
    const existing = await db.college.findUnique({
      where: { slug: college.slug },
    });

    if (existing) {
      await db.college.update({
        where: { slug: college.slug },
        data: college,
      });
      console.log(`Updated: ${college.name}`);
      updated++;
    } else {
      await db.college.create({
        data: college,
      });
      console.log(`Added: ${college.name}`);
      added++;
    }
  }

  console.log(`\n✓ Added ${added} new colleges`);
  console.log(`✓ Updated ${updated} existing colleges`);

  // Show new total
  const total = await db.college.count();
  console.log(`\nTotal colleges in database: ${total}`);

  await db.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
