/**
 * Add more notable colleges to the database - Batch 3
 * Focus on: HBCUs, more state universities, and additional selective schools
 * Data sourced from Common Data Set 2023-2024, IPEDS, and institutional websites
 */

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

interface CollegeData {
  name: string;
  slug: string;
  location: string;
  setting: string;
  institutionalSector: string;
  undergraduateEnrollment: number;
  studentsAdmittedPercent: number;
  costOfAttendanceInState: number;
  costOfAttendanceOutOfState: number;
  studentFacultyRatio: string;
  admissionsSelectivity: string;
  testPolicy: string;
  retentionRate: number;
  graduationRate4yr: number;
  graduationRate6yr: number;
  medianEarnings10yr: number;
  website: string;
  description: string;
  popularMajors: string;
  satScores: string;
  actScores: string;
  totalApplicants: number;
  totalAdmitted: number;
  totalEnrolled: number;
  yieldRate: number;
  rdDeadline: string;
  eaDeadline?: string;
  edDeadline?: string;
  earlyActionType?: string;
  fafsaRequired: boolean;
  cssProfileRequired: boolean;
  averageNetPrice: number;
  genderDistribution: string;
  raceEthnicity: string;
  admissionConsiderations: string;
  primaryColor: string;
  secondaryColor?: string;
}

const newColleges: CollegeData[] = [
  // Historically Black Colleges and Universities (HBCUs)
  {
    name: "Howard University",
    slug: "howard-university",
    location: "Washington, DC",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 9689,
    studentsAdmittedPercent: 53,
    costOfAttendanceInState: 52891,
    costOfAttendanceOutOfState: 52891,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 87,
    graduationRate4yr: 52,
    graduationRate6yr: 66,
    medianEarnings10yr: 56000,
    website: "https://www.howard.edu",
    description: "Howard University is a private, federally chartered historically Black university in Washington, D.C. Founded in 1867, it is one of the most prestigious HBCUs in the nation, known for producing leaders in law, medicine, business, and the arts. Notable alumni include Thurgood Marshall, Kamala Harris, and Toni Morrison.",
    popularMajors: JSON.stringify(["Biology", "Nursing", "Psychology", "Communications", "Political Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 570, max: 670 }, math: { min: 550, max: 640 }, total: { min: 1120, max: 1310 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 28 }, percentSubmitted: 15 }),
    totalApplicants: 33248,
    totalAdmitted: 17621,
    totalEnrolled: 2450,
    yieldRate: 13.9,
    rdDeadline: "February 15",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 28000,
    genderDistribution: JSON.stringify({ women: 67, men: 33 }),
    raceEthnicity: JSON.stringify({ Black: 86, "Two or More Races": 4, White: 2, Hispanic: 2, Asian: 1, International: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#003A63",
    secondaryColor: "#E51937"
  },
  {
    name: "Spelman College",
    slug: "spelman-college",
    location: "Atlanta, GA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2350,
    studentsAdmittedPercent: 29,
    costOfAttendanceInState: 51944,
    costOfAttendanceOutOfState: 51944,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 90,
    graduationRate4yr: 70,
    graduationRate6yr: 78,
    medianEarnings10yr: 52000,
    website: "https://www.spelman.edu",
    description: "Spelman College is a private historically Black women's liberal arts college in Atlanta, Georgia. Founded in 1881, it is the oldest historically Black college for women in the United States. Spelman consistently ranks as the top HBCU in the nation and is known for producing leaders in STEM, business, and public service.",
    popularMajors: JSON.stringify(["Biology", "Psychology", "Political Science", "Economics", "Computer Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 590, max: 680 }, math: { min: 560, max: 650 }, total: { min: 1150, max: 1330 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 28 }, percentSubmitted: 15 }),
    totalApplicants: 14000,
    totalAdmitted: 4060,
    totalEnrolled: 610,
    yieldRate: 15.0,
    rdDeadline: "February 1",
    edDeadline: "November 1",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 26000,
    genderDistribution: JSON.stringify({ women: 100, men: 0 }),
    raceEthnicity: JSON.stringify({ Black: 93, "Two or More Races": 3, Hispanic: 1, International: 3 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#003057"
  },
  {
    name: "Morehouse College",
    slug: "morehouse-college",
    location: "Atlanta, GA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2200,
    studentsAdmittedPercent: 45,
    costOfAttendanceInState: 53068,
    costOfAttendanceOutOfState: 53068,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 84,
    graduationRate4yr: 52,
    graduationRate6yr: 63,
    medianEarnings10yr: 48000,
    website: "https://www.morehouse.edu",
    description: "Morehouse College is a private historically Black men's liberal arts college in Atlanta, Georgia. Founded in 1867, it is the only historically Black college that is exclusively for men. Known as 'The House,' Morehouse has produced numerous influential leaders including Martin Luther King Jr., Spike Lee, and Samuel L. Jackson.",
    popularMajors: JSON.stringify(["Business Administration", "Biology", "Computer Science", "Political Science", "Psychology"]),
    satScores: JSON.stringify({ readingWriting: { min: 530, max: 620 }, math: { min: 510, max: 600 }, total: { min: 1040, max: 1220 }, percentSubmitted: 25 }),
    actScores: JSON.stringify({ composite: { min: 20, max: 26 }, percentSubmitted: 15 }),
    totalApplicants: 8500,
    totalAdmitted: 3825,
    totalEnrolled: 700,
    yieldRate: 18.3,
    rdDeadline: "February 15",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 28000,
    genderDistribution: JSON.stringify({ women: 0, men: 100 }),
    raceEthnicity: JSON.stringify({ Black: 95, "Two or More Races": 2, Hispanic: 1, International: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#660000"
  },
  {
    name: "Hampton University",
    slug: "hampton-university",
    location: "Hampton, VA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 3500,
    studentsAdmittedPercent: 42,
    costOfAttendanceInState: 43926,
    costOfAttendanceOutOfState: 43926,
    studentFacultyRatio: "14:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 80,
    graduationRate4yr: 47,
    graduationRate6yr: 58,
    medianEarnings10yr: 45000,
    website: "https://www.hamptonu.edu",
    description: "Hampton University is a private historically Black university in Hampton, Virginia. Founded in 1868, it has a strong tradition in the sciences and education. Hampton was one of the first HBCUs to offer a PhD program and is known for its architecture program and strong STEM offerings.",
    popularMajors: JSON.stringify(["Nursing", "Biology", "Business Administration", "Psychology", "Communications"]),
    satScores: JSON.stringify({ readingWriting: { min: 500, max: 580 }, math: { min: 480, max: 560 }, total: { min: 980, max: 1140 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 18, max: 23 }, percentSubmitted: 20 }),
    totalApplicants: 12000,
    totalAdmitted: 5040,
    totalEnrolled: 950,
    yieldRate: 18.8,
    rdDeadline: "March 1",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 22000,
    genderDistribution: JSON.stringify({ women: 66, men: 34 }),
    raceEthnicity: JSON.stringify({ Black: 92, "Two or More Races": 3, White: 2, Hispanic: 1, International: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#003366"
  },
  {
    name: "Florida A&M University",
    slug: "florida-am-university",
    location: "Tallahassee, FL",
    setting: "Urban",
    institutionalSector: "Public",
    undergraduateEnrollment: 8900,
    studentsAdmittedPercent: 42,
    costOfAttendanceInState: 18296,
    costOfAttendanceOutOfState: 35596,
    studentFacultyRatio: "16:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 85,
    graduationRate4yr: 31,
    graduationRate6yr: 49,
    medianEarnings10yr: 42000,
    website: "https://www.famu.edu",
    description: "Florida A&M University (FAMU) is a public historically Black university in Tallahassee, Florida. Founded in 1887, it is the largest HBCU by student enrollment and is known for its strong programs in pharmacy, engineering, business, and journalism. FAMU's Marching 100 band is world-renowned.",
    popularMajors: JSON.stringify(["Business Administration", "Biology", "Criminal Justice", "Psychology", "Engineering"]),
    satScores: JSON.stringify({ readingWriting: { min: 530, max: 610 }, math: { min: 500, max: 580 }, total: { min: 1030, max: 1190 }, percentSubmitted: 25 }),
    actScores: JSON.stringify({ composite: { min: 20, max: 24 }, percentSubmitted: 15 }),
    totalApplicants: 11500,
    totalAdmitted: 4830,
    totalEnrolled: 1950,
    yieldRate: 40.4,
    rdDeadline: "May 1",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 14000,
    genderDistribution: JSON.stringify({ women: 64, men: 36 }),
    raceEthnicity: JSON.stringify({ Black: 90, Hispanic: 3, "Two or More Races": 3, White: 2, International: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#F48320",
    secondaryColor: "#006F3D"
  },

  // More State Universities
  {
    name: "University of Alabama",
    slug: "university-of-alabama",
    location: "Tuscaloosa, AL",
    setting: "Suburban",
    institutionalSector: "Public",
    undergraduateEnrollment: 32400,
    studentsAdmittedPercent: 80,
    costOfAttendanceInState: 32900,
    costOfAttendanceOutOfState: 53500,
    studentFacultyRatio: "19:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 87,
    graduationRate4yr: 54,
    graduationRate6yr: 73,
    medianEarnings10yr: 52000,
    website: "https://www.ua.edu",
    description: "The University of Alabama is the flagship public university of Alabama, located in Tuscaloosa. Founded in 1831, it is known for its strong business, engineering, law, and nursing programs. UA is famous for its Crimson Tide athletics, particularly its dominant football program, and offers generous out-of-state scholarships.",
    popularMajors: JSON.stringify(["Business Administration", "Nursing", "Engineering", "Communications", "Psychology"]),
    satScores: JSON.stringify({ readingWriting: { min: 580, max: 680 }, math: { min: 560, max: 680 }, total: { min: 1140, max: 1360 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 24, max: 31 }, percentSubmitted: 45 }),
    totalApplicants: 48000,
    totalAdmitted: 38400,
    totalEnrolled: 8100,
    yieldRate: 21.1,
    rdDeadline: "Rolling",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 22000,
    genderDistribution: JSON.stringify({ women: 55, men: 45 }),
    raceEthnicity: JSON.stringify({ White: 74, Black: 11, Hispanic: 5, "Two or More Races": 4, Asian: 2, International: 4 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#9E1B32"
  },
  {
    name: "University of Tennessee Knoxville",
    slug: "university-of-tennessee-knoxville",
    location: "Knoxville, TN",
    setting: "Urban",
    institutionalSector: "Public",
    undergraduateEnrollment: 27500,
    studentsAdmittedPercent: 75,
    costOfAttendanceInState: 29816,
    costOfAttendanceOutOfState: 49456,
    studentFacultyRatio: "17:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 88,
    graduationRate4yr: 52,
    graduationRate6yr: 73,
    medianEarnings10yr: 51000,
    website: "https://www.utk.edu",
    description: "The University of Tennessee, Knoxville is the flagship campus of the University of Tennessee system. Founded in 1794, it is one of the oldest public universities in the nation. UTK is known for strong programs in engineering, business, and supply chain management, and has close ties to Oak Ridge National Laboratory.",
    popularMajors: JSON.stringify(["Business Administration", "Nursing", "Engineering", "Psychology", "Biology"]),
    satScores: JSON.stringify({ readingWriting: { min: 580, max: 680 }, math: { min: 560, max: 670 }, total: { min: 1140, max: 1350 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 24, max: 30 }, percentSubmitted: 55 }),
    totalApplicants: 28000,
    totalAdmitted: 21000,
    totalEnrolled: 5800,
    yieldRate: 27.6,
    rdDeadline: "December 15",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 18000,
    genderDistribution: JSON.stringify({ women: 51, men: 49 }),
    raceEthnicity: JSON.stringify({ White: 78, Black: 6, Hispanic: 5, "Two or More Races": 4, Asian: 3, International: 4 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#FF8200"
  },
  {
    name: "University of Arkansas",
    slug: "university-of-arkansas",
    location: "Fayetteville, AR",
    setting: "Suburban",
    institutionalSector: "Public",
    undergraduateEnrollment: 24500,
    studentsAdmittedPercent: 76,
    costOfAttendanceInState: 26530,
    costOfAttendanceOutOfState: 46020,
    studentFacultyRatio: "18:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 84,
    graduationRate4yr: 46,
    graduationRate6yr: 68,
    medianEarnings10yr: 49000,
    website: "https://www.uark.edu",
    description: "The University of Arkansas is the flagship campus of the University of Arkansas System. Founded in 1871, it is located in Fayetteville in the Ozark Mountains region. UA is known for its business school (Sam M. Walton College), engineering programs, and agricultural sciences. The university has strong ties to Walmart and Tyson Foods.",
    popularMajors: JSON.stringify(["Business Administration", "Engineering", "Nursing", "Biology", "Communications"]),
    satScores: JSON.stringify({ readingWriting: { min: 560, max: 660 }, math: { min: 550, max: 660 }, total: { min: 1110, max: 1320 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 60 }),
    totalApplicants: 26000,
    totalAdmitted: 19760,
    totalEnrolled: 5200,
    yieldRate: 26.3,
    rdDeadline: "August 1",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 17000,
    genderDistribution: JSON.stringify({ women: 54, men: 46 }),
    raceEthnicity: JSON.stringify({ White: 74, Hispanic: 8, "Two or More Races": 5, Black: 4, Asian: 3, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#9D2235"
  },
  {
    name: "University of Mississippi",
    slug: "university-of-mississippi",
    location: "Oxford, MS",
    setting: "Small Town",
    institutionalSector: "Public",
    undergraduateEnrollment: 17900,
    studentsAdmittedPercent: 88,
    costOfAttendanceInState: 25740,
    costOfAttendanceOutOfState: 43540,
    studentFacultyRatio: "17:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 84,
    graduationRate4yr: 48,
    graduationRate6yr: 66,
    medianEarnings10yr: 46000,
    website: "https://www.olemiss.edu",
    description: "The University of Mississippi, affectionately known as 'Ole Miss,' is the flagship public university of Mississippi. Founded in 1848, it is located in the historic town of Oxford. Ole Miss is known for its strong programs in accountancy, pharmacy, and law, and has a vibrant campus culture and strong Southern traditions.",
    popularMajors: JSON.stringify(["Business Administration", "Accountancy", "Biology", "Nursing", "Engineering"]),
    satScores: JSON.stringify({ readingWriting: { min: 540, max: 640 }, math: { min: 520, max: 630 }, total: { min: 1060, max: 1270 }, percentSubmitted: 25 }),
    actScores: JSON.stringify({ composite: { min: 22, max: 28 }, percentSubmitted: 65 }),
    totalApplicants: 22000,
    totalAdmitted: 19360,
    totalEnrolled: 3900,
    yieldRate: 20.1,
    rdDeadline: "Rolling",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 18000,
    genderDistribution: JSON.stringify({ women: 58, men: 42 }),
    raceEthnicity: JSON.stringify({ White: 73, Black: 12, Hispanic: 4, "Two or More Races": 3, Asian: 2, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#CE1126",
    secondaryColor: "#14213D"
  },
  {
    name: "Louisiana State University",
    slug: "louisiana-state-university",
    location: "Baton Rouge, LA",
    setting: "Urban",
    institutionalSector: "Public",
    undergraduateEnrollment: 29000,
    studentsAdmittedPercent: 74,
    costOfAttendanceInState: 28946,
    costOfAttendanceOutOfState: 47066,
    studentFacultyRatio: "19:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 84,
    graduationRate4yr: 46,
    graduationRate6yr: 67,
    medianEarnings10yr: 48000,
    website: "https://www.lsu.edu",
    description: "Louisiana State University is the flagship public university of Louisiana, located in Baton Rouge. Founded in 1853, LSU is known for its strong programs in petroleum engineering, business, and agricultural sciences. The university's Tiger Stadium ('Death Valley') is one of the most iconic college football venues in America.",
    popularMajors: JSON.stringify(["Business Administration", "Engineering", "Biology", "Psychology", "Mass Communication"]),
    satScores: JSON.stringify({ readingWriting: { min: 570, max: 660 }, math: { min: 560, max: 660 }, total: { min: 1130, max: 1320 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 55 }),
    totalApplicants: 26000,
    totalAdmitted: 19240,
    totalEnrolled: 5800,
    yieldRate: 30.1,
    rdDeadline: "April 15",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 19000,
    genderDistribution: JSON.stringify({ women: 54, men: 46 }),
    raceEthnicity: JSON.stringify({ White: 70, Black: 13, Hispanic: 7, Asian: 4, "Two or More Races": 3, International: 3 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#461D7C",
    secondaryColor: "#FDD023"
  },

  // Additional Selective Private Universities
  {
    name: "American University",
    slug: "american-university",
    location: "Washington, DC",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 8200,
    studentsAdmittedPercent: 44,
    costOfAttendanceInState: 76884,
    costOfAttendanceOutOfState: 76884,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 88,
    graduationRate4yr: 75,
    graduationRate6yr: 82,
    medianEarnings10yr: 60000,
    website: "https://www.american.edu",
    description: "American University is a private research university in Washington, D.C. Founded in 1893, it is known for its strong programs in international relations, political science, public affairs, and communications. AU's location in the nation's capital provides unparalleled access to government, nonprofit, and international organizations.",
    popularMajors: JSON.stringify(["International Studies", "Political Science", "Business Administration", "Communications", "Psychology"]),
    satScores: JSON.stringify({ readingWriting: { min: 640, max: 720 }, math: { min: 610, max: 710 }, total: { min: 1250, max: 1430 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 28, max: 32 }, percentSubmitted: 20 }),
    totalApplicants: 22000,
    totalAdmitted: 9680,
    totalEnrolled: 1850,
    yieldRate: 19.1,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 42000,
    genderDistribution: JSON.stringify({ women: 64, men: 36 }),
    raceEthnicity: JSON.stringify({ White: 52, Hispanic: 14, Asian: 8, Black: 7, "Two or More Races": 6, International: 13 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#C41230"
  },
  {
    name: "George Washington University",
    slug: "george-washington-university",
    location: "Washington, DC",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 12500,
    studentsAdmittedPercent: 49,
    costOfAttendanceInState: 82780,
    costOfAttendanceOutOfState: 82780,
    studentFacultyRatio: "12:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 91,
    graduationRate4yr: 76,
    graduationRate6yr: 84,
    medianEarnings10yr: 68000,
    website: "https://www.gwu.edu",
    description: "George Washington University is a private research university in Washington, D.C. Founded in 1821, GW has an urban campus located blocks from the White House. It is renowned for its programs in political science, international affairs, public health, and business. GW provides exceptional internship and career opportunities due to its prime location.",
    popularMajors: JSON.stringify(["Political Science", "International Affairs", "Business Administration", "Psychology", "Public Health"]),
    satScores: JSON.stringify({ readingWriting: { min: 660, max: 730 }, math: { min: 640, max: 740 }, total: { min: 1300, max: 1470 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 30, max: 33 }, percentSubmitted: 20 }),
    totalApplicants: 27000,
    totalAdmitted: 13230,
    totalEnrolled: 2600,
    yieldRate: 19.7,
    rdDeadline: "January 5",
    edDeadline: "November 1",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 59, men: 41 }),
    raceEthnicity: JSON.stringify({ White: 48, Asian: 11, Hispanic: 11, Black: 8, "Two or More Races": 5, International: 17 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#004065",
    secondaryColor: "#AA9868"
  },
  {
    name: "Fordham University",
    slug: "fordham-university",
    location: "New York, NY",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 10200,
    studentsAdmittedPercent: 54,
    costOfAttendanceInState: 81130,
    costOfAttendanceOutOfState: 81130,
    studentFacultyRatio: "14:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 90,
    graduationRate4yr: 78,
    graduationRate6yr: 83,
    medianEarnings10yr: 69000,
    website: "https://www.fordham.edu",
    description: "Fordham University is a private Jesuit research university with campuses in the Bronx and Manhattan. Founded in 1841, it is one of the oldest Catholic universities in the northeastern United States. Fordham is known for its strong programs in business, law, and communications, and its urban New York City location provides exceptional career opportunities.",
    popularMajors: JSON.stringify(["Business Administration", "Communications", "Biology", "Psychology", "Political Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 640, max: 720 }, math: { min: 630, max: 720 }, total: { min: 1270, max: 1440 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 29, max: 33 }, percentSubmitted: 25 }),
    totalApplicants: 50000,
    totalAdmitted: 27000,
    totalEnrolled: 2400,
    yieldRate: 8.9,
    rdDeadline: "January 1",
    edDeadline: "November 1",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 42000,
    genderDistribution: JSON.stringify({ women: 58, men: 42 }),
    raceEthnicity: JSON.stringify({ White: 50, Hispanic: 18, Asian: 11, Black: 6, "Two or More Races": 5, International: 10 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#900028"
  },
  {
    name: "Loyola Marymount University",
    slug: "loyola-marymount-university",
    location: "Los Angeles, CA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 7200,
    studentsAdmittedPercent: 45,
    costOfAttendanceInState: 76826,
    costOfAttendanceOutOfState: 76826,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 91,
    graduationRate4yr: 74,
    graduationRate6yr: 83,
    medianEarnings10yr: 67000,
    website: "https://www.lmu.edu",
    description: "Loyola Marymount University is a private Jesuit university in Los Angeles, California. Founded in 1911, it is the parent school of the LMU Loyola Law School. LMU is known for its strong programs in business, film, and communications, and its beautiful bluff-top campus overlooking the Pacific Ocean.",
    popularMajors: JSON.stringify(["Business Administration", "Film and Television", "Communications", "Psychology", "Biology"]),
    satScores: JSON.stringify({ readingWriting: { min: 620, max: 710 }, math: { min: 610, max: 710 }, total: { min: 1230, max: 1420 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 27, max: 32 }, percentSubmitted: 25 }),
    totalApplicants: 18000,
    totalAdmitted: 8100,
    totalEnrolled: 1600,
    yieldRate: 19.8,
    rdDeadline: "January 15",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 46000,
    genderDistribution: JSON.stringify({ women: 56, men: 44 }),
    raceEthnicity: JSON.stringify({ White: 42, Hispanic: 25, Asian: 11, "Two or More Races": 9, Black: 5, International: 8 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#00355F",
    secondaryColor: "#8B2131"
  },
  {
    name: "Marquette University",
    slug: "marquette-university",
    location: "Milwaukee, WI",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 7800,
    studentsAdmittedPercent: 83,
    costOfAttendanceInState: 62978,
    costOfAttendanceOutOfState: 62978,
    studentFacultyRatio: "14:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 88,
    graduationRate4yr: 67,
    graduationRate6yr: 82,
    medianEarnings10yr: 58000,
    website: "https://www.marquette.edu",
    description: "Marquette University is a private Jesuit university in Milwaukee, Wisconsin. Founded in 1881, it is the largest Jesuit university in the country. Marquette is known for its strong programs in nursing, business, engineering, and physical therapy. The university emphasizes service and community engagement in the Jesuit tradition.",
    popularMajors: JSON.stringify(["Nursing", "Business Administration", "Engineering", "Biology", "Communications"]),
    satScores: JSON.stringify({ readingWriting: { min: 580, max: 680 }, math: { min: 580, max: 690 }, total: { min: 1160, max: 1370 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 25, max: 30 }, percentSubmitted: 45 }),
    totalApplicants: 15000,
    totalAdmitted: 12450,
    totalEnrolled: 1900,
    yieldRate: 15.3,
    rdDeadline: "Rolling",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 36000,
    genderDistribution: JSON.stringify({ women: 55, men: 45 }),
    raceEthnicity: JSON.stringify({ White: 71, Hispanic: 10, Black: 5, Asian: 5, "Two or More Races": 4, International: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#003366",
    secondaryColor: "#F7C900"
  },

  // More Liberal Arts Colleges
  {
    name: "Denison University",
    slug: "denison-university",
    location: "Granville, OH",
    setting: "Rural",
    institutionalSector: "Private",
    undergraduateEnrollment: 2350,
    studentsAdmittedPercent: 30,
    costOfAttendanceInState: 74490,
    costOfAttendanceOutOfState: 74490,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 90,
    graduationRate4yr: 79,
    graduationRate6yr: 84,
    medianEarnings10yr: 55000,
    website: "https://www.denison.edu",
    description: "Denison University is a private liberal arts college in Granville, Ohio. Founded in 1831, it is one of the oldest liberal arts colleges in the country. Denison is known for its strong programs in economics, political science, and the sciences, and emphasizes undergraduate research and interdisciplinary learning.",
    popularMajors: JSON.stringify(["Economics", "Political Science", "Biology", "Psychology", "Communications"]),
    satScores: JSON.stringify({ readingWriting: { min: 640, max: 720 }, math: { min: 630, max: 720 }, total: { min: 1270, max: 1440 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 28, max: 32 }, percentSubmitted: 25 }),
    totalApplicants: 10500,
    totalAdmitted: 3150,
    totalEnrolled: 630,
    yieldRate: 20.0,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 36000,
    genderDistribution: JSON.stringify({ women: 54, men: 46 }),
    raceEthnicity: JSON.stringify({ White: 63, Hispanic: 9, Black: 8, Asian: 5, "Two or More Races": 5, International: 10 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#C41230"
  },
  {
    name: "Dickinson College",
    slug: "dickinson-college",
    location: "Carlisle, PA",
    setting: "Small Town",
    institutionalSector: "Private",
    undergraduateEnrollment: 2200,
    studentsAdmittedPercent: 41,
    costOfAttendanceInState: 76364,
    costOfAttendanceOutOfState: 76364,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 90,
    graduationRate4yr: 80,
    graduationRate6yr: 85,
    medianEarnings10yr: 58000,
    website: "https://www.dickinson.edu",
    description: "Dickinson College is a private liberal arts college in Carlisle, Pennsylvania. Founded in 1783, it was the first college chartered in the newly independent United States. Dickinson is known for its emphasis on global education and sustainability, with strong programs in international studies, environmental science, and languages.",
    popularMajors: JSON.stringify(["International Business & Management", "Political Science", "Economics", "Psychology", "Biology"]),
    satScores: JSON.stringify({ readingWriting: { min: 640, max: 720 }, math: { min: 620, max: 710 }, total: { min: 1260, max: 1430 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 28, max: 32 }, percentSubmitted: 20 }),
    totalApplicants: 8200,
    totalAdmitted: 3362,
    totalEnrolled: 580,
    yieldRate: 17.3,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 57, men: 43 }),
    raceEthnicity: JSON.stringify({ White: 65, Hispanic: 9, Black: 6, Asian: 5, "Two or More Races": 5, International: 10 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#C41230"
  },
  {
    name: "Franklin & Marshall College",
    slug: "franklin-marshall-college",
    location: "Lancaster, PA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2200,
    studentsAdmittedPercent: 33,
    costOfAttendanceInState: 77740,
    costOfAttendanceOutOfState: 77740,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 91,
    graduationRate4yr: 80,
    graduationRate6yr: 86,
    medianEarnings10yr: 62000,
    website: "https://www.fandm.edu",
    description: "Franklin & Marshall College is a private liberal arts college in Lancaster, Pennsylvania. Founded in 1787, it is one of the oldest colleges in the United States. F&M is known for its strong pre-med and pre-law programs, as well as its emphasis on undergraduate research. The college has a strong tradition in government and business.",
    popularMajors: JSON.stringify(["Government", "Business Organizations and Society", "Biology", "Psychology", "Economics"]),
    satScores: JSON.stringify({ readingWriting: { min: 650, max: 730 }, math: { min: 650, max: 740 }, total: { min: 1300, max: 1470 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 29, max: 33 }, percentSubmitted: 20 }),
    totalApplicants: 9800,
    totalAdmitted: 3234,
    totalEnrolled: 620,
    yieldRate: 19.2,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 32000,
    genderDistribution: JSON.stringify({ women: 52, men: 48 }),
    raceEthnicity: JSON.stringify({ White: 55, Hispanic: 13, Asian: 8, Black: 7, "Two or More Races": 5, International: 12 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Important"
    }),
    primaryColor: "#003A70"
  },
  {
    name: "Gettysburg College",
    slug: "gettysburg-college",
    location: "Gettysburg, PA",
    setting: "Small Town",
    institutionalSector: "Private",
    undergraduateEnrollment: 2400,
    studentsAdmittedPercent: 48,
    costOfAttendanceInState: 75880,
    costOfAttendanceOutOfState: 75880,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 89,
    graduationRate4yr: 79,
    graduationRate6yr: 84,
    medianEarnings10yr: 63000,
    website: "https://www.gettysburg.edu",
    description: "Gettysburg College is a private liberal arts college located in Gettysburg, Pennsylvania, the site of the famous Civil War battle. Founded in 1832, it is known for its strong programs in history, political science, and the sciences. The college emphasizes engaged learning and has a strong tradition of service and leadership.",
    popularMajors: JSON.stringify(["Political Science", "Business", "History", "Biology", "Psychology"]),
    satScores: JSON.stringify({ readingWriting: { min: 620, max: 700 }, math: { min: 610, max: 700 }, total: { min: 1230, max: 1400 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 27, max: 31 }, percentSubmitted: 20 }),
    totalApplicants: 7500,
    totalAdmitted: 3600,
    totalEnrolled: 680,
    yieldRate: 18.9,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 54, men: 46 }),
    raceEthnicity: JSON.stringify({ White: 72, Hispanic: 7, Black: 5, Asian: 4, "Two or More Races": 4, International: 8 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#F26522",
    secondaryColor: "#00457C"
  },
  {
    name: "Rhodes College",
    slug: "rhodes-college",
    location: "Memphis, TN",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2000,
    studentsAdmittedPercent: 50,
    costOfAttendanceInState: 66000,
    costOfAttendanceOutOfState: 66000,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 87,
    graduationRate4yr: 74,
    graduationRate6yr: 82,
    medianEarnings10yr: 52000,
    website: "https://www.rhodes.edu",
    description: "Rhodes College is a private liberal arts college in Memphis, Tennessee. Founded in 1848, it is known for its stunning Gothic architecture and strong programs in the humanities, sciences, and business. Rhodes emphasizes service learning and community engagement, with close ties to Memphis institutions including St. Jude Children's Research Hospital.",
    popularMajors: JSON.stringify(["Biology", "Business", "Psychology", "Political Science", "English"]),
    satScores: JSON.stringify({ readingWriting: { min: 620, max: 710 }, math: { min: 600, max: 700 }, total: { min: 1220, max: 1410 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 27, max: 32 }, percentSubmitted: 45 }),
    totalApplicants: 6500,
    totalAdmitted: 3250,
    totalEnrolled: 520,
    yieldRate: 16.0,
    rdDeadline: "January 15",
    edDeadline: "November 1",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 34000,
    genderDistribution: JSON.stringify({ women: 56, men: 44 }),
    raceEthnicity: JSON.stringify({ White: 70, Black: 9, Hispanic: 6, Asian: 5, "Two or More Races": 4, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Important"
    }),
    primaryColor: "#9D2235"
  },
  {
    name: "Centre College",
    slug: "centre-college",
    location: "Danville, KY",
    setting: "Small Town",
    institutionalSector: "Private",
    undergraduateEnrollment: 1400,
    studentsAdmittedPercent: 64,
    costOfAttendanceInState: 62800,
    costOfAttendanceOutOfState: 62800,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 89,
    graduationRate4yr: 79,
    graduationRate6yr: 84,
    medianEarnings10yr: 56000,
    website: "https://www.centre.edu",
    description: "Centre College is a private liberal arts college in Danville, Kentucky. Founded in 1819, it is one of the oldest colleges west of the Allegheny Mountains. Centre is known for its strong programs in economics, biology, and government, and guarantees students study abroad, an internship, and graduation in four years.",
    popularMajors: JSON.stringify(["Economics & Finance", "Biology", "Government", "Psychology", "History"]),
    satScores: JSON.stringify({ readingWriting: { min: 600, max: 690 }, math: { min: 590, max: 690 }, total: { min: 1190, max: 1380 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 26, max: 31 }, percentSubmitted: 50 }),
    totalApplicants: 3500,
    totalAdmitted: 2240,
    totalEnrolled: 400,
    yieldRate: 17.9,
    rdDeadline: "January 15",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 30000,
    genderDistribution: JSON.stringify({ women: 51, men: 49 }),
    raceEthnicity: JSON.stringify({ White: 78, Hispanic: 6, Black: 5, Asian: 3, "Two or More Races": 3, International: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Important"
    }),
    primaryColor: "#FFD100",
    secondaryColor: "#333333"
  }
];

async function main() {
  console.log("Adding new colleges to database - Batch 3...\n");

  let added = 0;
  let updated = 0;

  for (const college of newColleges) {
    const existing = await db.college.findUnique({
      where: { slug: college.slug },
    });

    if (existing) {
      // Update existing college with new data
      await db.college.update({
        where: { slug: college.slug },
        data: college,
      });
      console.log(`Updated: ${college.name}`);
      updated++;
    } else {
      // Add new college
      await db.college.create({
        data: college,
      });
      console.log(`Added: ${college.name}`);
      added++;
    }
  }

  const totalColleges = await db.college.count();
  console.log(`\n✓ Added ${added} new colleges`);
  console.log(`✓ Updated ${updated} existing colleges`);
  console.log(`Total colleges in database: ${totalColleges}`);

  await db.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
