/**
 * Add more notable colleges to the database - Batch 5
 * Focus on: More LACs, tech-focused schools, and additional notable universities
 * Data sourced from Common Data Set 2023-2024, IPEDS, and institutional websites
 */

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

interface CollegeData {
  name: string;
  slug: string;
  location: string;
  setting: string;
  institutionalSector: string;
  undergraduateEnrollment: number;
  studentsAdmittedPercent: number;
  costOfAttendanceInState: number;
  costOfAttendanceOutOfState: number;
  studentFacultyRatio: string;
  admissionsSelectivity: string;
  testPolicy: string;
  retentionRate: number;
  graduationRate4yr: number;
  graduationRate6yr: number;
  medianEarnings10yr: number;
  website: string;
  description: string;
  popularMajors: string;
  satScores: string;
  actScores: string;
  totalApplicants: number;
  totalAdmitted: number;
  totalEnrolled: number;
  yieldRate: number;
  rdDeadline: string;
  eaDeadline?: string;
  edDeadline?: string;
  earlyActionType?: string;
  fafsaRequired: boolean;
  cssProfileRequired: boolean;
  averageNetPrice: number;
  genderDistribution: string;
  raceEthnicity: string;
  admissionConsiderations: string;
  primaryColor: string;
  secondaryColor?: string;
}

const newColleges: CollegeData[] = [
  // More Tech-focused Schools
  {
    name: "Illinois Institute of Technology",
    slug: "illinois-institute-of-technology",
    location: "Chicago, IL",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 3000,
    studentsAdmittedPercent: 58,
    costOfAttendanceInState: 68616,
    costOfAttendanceOutOfState: 68616,
    studentFacultyRatio: "12:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 88,
    graduationRate4yr: 52,
    graduationRate6yr: 72,
    medianEarnings10yr: 78000,
    website: "https://www.iit.edu",
    description: "Illinois Institute of Technology (Illinois Tech) is a private research university in Chicago. Founded in 1890, it is known for its strong engineering, architecture, and computer science programs. The campus was designed by Ludwig Mies van der Rohe and is a National Historic Landmark.",
    popularMajors: JSON.stringify(["Computer Science", "Mechanical Engineering", "Electrical Engineering", "Architecture", "Aerospace Engineering"]),
    satScores: JSON.stringify({ readingWriting: { min: 600, max: 700 }, math: { min: 640, max: 760 }, total: { min: 1240, max: 1460 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 27, max: 33 }, percentSubmitted: 40 }),
    totalApplicants: 7500,
    totalAdmitted: 4350,
    totalEnrolled: 650,
    yieldRate: 14.9,
    rdDeadline: "Rolling",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 36000,
    genderDistribution: JSON.stringify({ women: 33, men: 67 }),
    raceEthnicity: JSON.stringify({ White: 28, Asian: 22, Hispanic: 18, International: 18, Black: 7, "Two or More Races": 7 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#CC0000"
  },
  {
    name: "New Jersey Institute of Technology",
    slug: "new-jersey-institute-of-technology",
    location: "Newark, NJ",
    setting: "Urban",
    institutionalSector: "Public",
    undergraduateEnrollment: 9200,
    studentsAdmittedPercent: 68,
    costOfAttendanceInState: 36638,
    costOfAttendanceOutOfState: 52638,
    studentFacultyRatio: "16:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 85,
    graduationRate4yr: 32,
    graduationRate6yr: 67,
    medianEarnings10yr: 75000,
    website: "https://www.njit.edu",
    description: "New Jersey Institute of Technology (NJIT) is a public research university in Newark, New Jersey. Founded in 1881, it is one of the top public technological universities in the nation. NJIT offers strong programs in engineering, computing, architecture, and applied sciences at relatively affordable tuition.",
    popularMajors: JSON.stringify(["Computer Science", "Information Technology", "Mechanical Engineering", "Civil Engineering", "Architecture"]),
    satScores: JSON.stringify({ readingWriting: { min: 570, max: 670 }, math: { min: 610, max: 720 }, total: { min: 1180, max: 1390 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 25, max: 31 }, percentSubmitted: 20 }),
    totalApplicants: 15000,
    totalAdmitted: 10200,
    totalEnrolled: 1800,
    yieldRate: 17.6,
    rdDeadline: "March 1",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 22000,
    genderDistribution: JSON.stringify({ women: 25, men: 75 }),
    raceEthnicity: JSON.stringify({ Asian: 30, White: 25, Hispanic: 22, Black: 10, "Two or More Races": 5, International: 8 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Considered",
      "Recommendation(s)": "Considered",
      "Extracurricular activities": "Considered",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Considered",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#D61024"
  },
  {
    name: "Clarkson University",
    slug: "clarkson-university",
    location: "Potsdam, NY",
    setting: "Rural",
    institutionalSector: "Private",
    undergraduateEnrollment: 3200,
    studentsAdmittedPercent: 72,
    costOfAttendanceInState: 72840,
    costOfAttendanceOutOfState: 72840,
    studentFacultyRatio: "12:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 87,
    graduationRate4yr: 60,
    graduationRate6yr: 74,
    medianEarnings10yr: 74000,
    website: "https://www.clarkson.edu",
    description: "Clarkson University is a private research university in Potsdam, New York. Founded in 1896, it is known for its strong engineering, business, and science programs. Clarkson has close ties to industry partners and strong job placement rates, particularly in engineering and supply chain management.",
    popularMajors: JSON.stringify(["Mechanical Engineering", "Civil Engineering", "Business Administration", "Computer Science", "Electrical Engineering"]),
    satScores: JSON.stringify({ readingWriting: { min: 570, max: 670 }, math: { min: 600, max: 710 }, total: { min: 1170, max: 1380 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 25, max: 31 }, percentSubmitted: 30 }),
    totalApplicants: 8500,
    totalAdmitted: 6120,
    totalEnrolled: 780,
    yieldRate: 12.7,
    rdDeadline: "February 1",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 30, men: 70 }),
    raceEthnicity: JSON.stringify({ White: 70, Asian: 8, Hispanic: 6, Black: 4, "Two or More Races": 4, International: 8 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#00602C",
    secondaryColor: "#F9A602"
  },

  // More Liberal Arts Colleges
  {
    name: "St. Olaf College",
    slug: "st-olaf-college",
    location: "Northfield, MN",
    setting: "Small Town",
    institutionalSector: "Private",
    undergraduateEnrollment: 2950,
    studentsAdmittedPercent: 49,
    costOfAttendanceInState: 68420,
    costOfAttendanceOutOfState: 68420,
    studentFacultyRatio: "12:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 91,
    graduationRate4yr: 82,
    graduationRate6yr: 87,
    medianEarnings10yr: 52000,
    website: "https://www.stolaf.edu",
    description: "St. Olaf College is a private liberal arts college in Northfield, Minnesota. Founded in 1874 by Norwegian immigrants, it maintains a strong connection to the Lutheran tradition. St. Olaf is renowned for its music programs, particularly its world-famous choir, and strong programs in mathematics and sciences.",
    popularMajors: JSON.stringify(["Biology", "Economics", "Mathematics", "Music", "Psychology"]),
    satScores: JSON.stringify({ readingWriting: { min: 620, max: 720 }, math: { min: 620, max: 740 }, total: { min: 1240, max: 1460 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 27, max: 32 }, percentSubmitted: 50 }),
    totalApplicants: 6800,
    totalAdmitted: 3332,
    totalEnrolled: 770,
    yieldRate: 23.1,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 34000,
    genderDistribution: JSON.stringify({ women: 56, men: 44 }),
    raceEthnicity: JSON.stringify({ White: 72, Asian: 8, Hispanic: 6, "Two or More Races": 5, Black: 3, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#FFCC00",
    secondaryColor: "#000000"
  },
  {
    name: "Gustavus Adolphus College",
    slug: "gustavus-adolphus-college",
    location: "St. Peter, MN",
    setting: "Small Town",
    institutionalSector: "Private",
    undergraduateEnrollment: 2100,
    studentsAdmittedPercent: 71,
    costOfAttendanceInState: 62530,
    costOfAttendanceOutOfState: 62530,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 85,
    graduationRate4yr: 73,
    graduationRate6yr: 80,
    medianEarnings10yr: 50000,
    website: "https://www.gustavus.edu",
    description: "Gustavus Adolphus College is a private liberal arts college in St. Peter, Minnesota. Founded in 1862 by Swedish Lutheran immigrants, it maintains strong Scandinavian traditions including the annual Nobel Conference. Gustavus is known for its strong programs in sciences, pre-med, and music.",
    popularMajors: JSON.stringify(["Biology", "Psychology", "Economics & Management", "Exercise Physiology", "Music"]),
    satScores: JSON.stringify({ readingWriting: { min: 550, max: 660 }, math: { min: 550, max: 670 }, total: { min: 1100, max: 1330 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 55 }),
    totalApplicants: 4500,
    totalAdmitted: 3195,
    totalEnrolled: 580,
    yieldRate: 18.2,
    rdDeadline: "Rolling",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 32000,
    genderDistribution: JSON.stringify({ women: 54, men: 46 }),
    raceEthnicity: JSON.stringify({ White: 80, Hispanic: 5, Asian: 4, Black: 3, "Two or More Races": 4, International: 4 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#231F20",
    secondaryColor: "#DFB84D"
  },
  {
    name: "Augustana College",
    slug: "augustana-college-il",
    location: "Rock Island, IL",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2300,
    studentsAdmittedPercent: 72,
    costOfAttendanceInState: 60550,
    costOfAttendanceOutOfState: 60550,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 84,
    graduationRate4yr: 71,
    graduationRate6yr: 78,
    medianEarnings10yr: 52000,
    website: "https://www.augustana.edu",
    description: "Augustana College is a private liberal arts college in Rock Island, Illinois. Founded in 1860 by Swedish Lutheran immigrants, it offers strong programs in sciences, business, and pre-professional studies. The college is located along the Mississippi River with a beautiful wooded campus.",
    popularMajors: JSON.stringify(["Biology", "Business Administration", "Psychology", "Accounting", "Pre-Medicine"]),
    satScores: JSON.stringify({ readingWriting: { min: 540, max: 650 }, math: { min: 540, max: 660 }, total: { min: 1080, max: 1310 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 22, max: 28 }, percentSubmitted: 55 }),
    totalApplicants: 5500,
    totalAdmitted: 3960,
    totalEnrolled: 640,
    yieldRate: 16.2,
    rdDeadline: "Rolling",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 28000,
    genderDistribution: JSON.stringify({ women: 58, men: 42 }),
    raceEthnicity: JSON.stringify({ White: 72, Hispanic: 12, Black: 5, Asian: 4, "Two or More Races": 4, International: 3 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#003366",
    secondaryColor: "#FFCC00"
  },
  {
    name: "Luther College",
    slug: "luther-college",
    location: "Decorah, IA",
    setting: "Rural",
    institutionalSector: "Private",
    undergraduateEnrollment: 1850,
    studentsAdmittedPercent: 73,
    costOfAttendanceInState: 58700,
    costOfAttendanceOutOfState: 58700,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 82,
    graduationRate4yr: 68,
    graduationRate6yr: 77,
    medianEarnings10yr: 46000,
    website: "https://www.luther.edu",
    description: "Luther College is a private liberal arts college in Decorah, Iowa. Founded in 1861, it maintains strong Norwegian Lutheran traditions and is known for its excellent music program. Luther's beautiful campus in the driftless region of Iowa offers extensive outdoor recreation opportunities.",
    popularMajors: JSON.stringify(["Biology", "Music", "Nursing", "Psychology", "Business Management"]),
    satScores: JSON.stringify({ readingWriting: { min: 530, max: 640 }, math: { min: 530, max: 650 }, total: { min: 1060, max: 1290 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 22, max: 28 }, percentSubmitted: 60 }),
    totalApplicants: 4200,
    totalAdmitted: 3066,
    totalEnrolled: 480,
    yieldRate: 15.7,
    rdDeadline: "Rolling",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 28000,
    genderDistribution: JSON.stringify({ women: 56, men: 44 }),
    raceEthnicity: JSON.stringify({ White: 82, Hispanic: 5, Asian: 3, Black: 3, "Two or More Races": 4, International: 3 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#002D62",
    secondaryColor: "#FFFFFF"
  },
  {
    name: "Earlham College",
    slug: "earlham-college",
    location: "Richmond, IN",
    setting: "Small Town",
    institutionalSector: "Private",
    undergraduateEnrollment: 800,
    studentsAdmittedPercent: 62,
    costOfAttendanceInState: 62180,
    costOfAttendanceOutOfState: 62180,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 78,
    graduationRate4yr: 58,
    graduationRate6yr: 68,
    medianEarnings10yr: 42000,
    website: "https://www.earlham.edu",
    description: "Earlham College is a private liberal arts college in Richmond, Indiana. Founded in 1847 by Quakers, it maintains a strong emphasis on consensus decision-making and social justice. Earlham is known for its strong programs in peace studies, international studies, and the sciences.",
    popularMajors: JSON.stringify(["Biology", "Psychology", "Peace and Global Studies", "Politics", "Environmental Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 550, max: 680 }, math: { min: 530, max: 660 }, total: { min: 1080, max: 1340 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 30 }, percentSubmitted: 30 }),
    totalApplicants: 2500,
    totalAdmitted: 1550,
    totalEnrolled: 220,
    yieldRate: 14.2,
    rdDeadline: "February 15",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 26000,
    genderDistribution: JSON.stringify({ women: 54, men: 46 }),
    raceEthnicity: JSON.stringify({ White: 52, International: 18, Black: 10, Hispanic: 8, "Two or More Races": 7, Asian: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Important"
    }),
    primaryColor: "#800020"
  },
  {
    name: "Lake Forest College",
    slug: "lake-forest-college",
    location: "Lake Forest, IL",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 1700,
    studentsAdmittedPercent: 59,
    costOfAttendanceInState: 67040,
    costOfAttendanceOutOfState: 67040,
    studentFacultyRatio: "12:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 82,
    graduationRate4yr: 64,
    graduationRate6yr: 71,
    medianEarnings10yr: 52000,
    website: "https://www.lakeforest.edu",
    description: "Lake Forest College is a private liberal arts college in Lake Forest, Illinois, north of Chicago. Founded in 1857, it offers strong programs in business, economics, and pre-professional studies. The college's proximity to Chicago provides excellent internship opportunities while maintaining a residential campus atmosphere.",
    popularMajors: JSON.stringify(["Business", "Economics", "Psychology", "Communications", "Biology"]),
    satScores: JSON.stringify({ readingWriting: { min: 560, max: 670 }, math: { min: 550, max: 670 }, total: { min: 1110, max: 1340 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 40 }),
    totalApplicants: 5500,
    totalAdmitted: 3245,
    totalEnrolled: 430,
    yieldRate: 13.2,
    rdDeadline: "Rolling",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 28000,
    genderDistribution: JSON.stringify({ women: 55, men: 45 }),
    raceEthnicity: JSON.stringify({ White: 48, Hispanic: 17, International: 12, Asian: 8, Black: 8, "Two or More Races": 7 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#A50034"
  },
  {
    name: "Knox College",
    slug: "knox-college",
    location: "Galesburg, IL",
    setting: "Small Town",
    institutionalSector: "Private",
    undergraduateEnrollment: 1100,
    studentsAdmittedPercent: 73,
    costOfAttendanceInState: 64500,
    costOfAttendanceOutOfState: 64500,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 82,
    graduationRate4yr: 66,
    graduationRate6yr: 74,
    medianEarnings10yr: 46000,
    website: "https://www.knox.edu",
    description: "Knox College is a private liberal arts college in Galesburg, Illinois. Founded in 1837 by abolitionists, it was a stop on the Underground Railroad. Knox is known for its strong creative writing program (one of the first undergraduate programs in the country) and its commitment to social activism.",
    popularMajors: JSON.stringify(["Creative Writing", "Psychology", "Biology", "Economics", "Political Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 560, max: 690 }, math: { min: 540, max: 670 }, total: { min: 1100, max: 1360 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 30 }, percentSubmitted: 35 }),
    totalApplicants: 3800,
    totalAdmitted: 2774,
    totalEnrolled: 320,
    yieldRate: 11.5,
    rdDeadline: "Rolling",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 26000,
    genderDistribution: JSON.stringify({ women: 55, men: 45 }),
    raceEthnicity: JSON.stringify({ White: 52, Hispanic: 15, International: 12, Black: 8, "Two or More Races": 7, Asian: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Important"
    }),
    primaryColor: "#461D7C"
  },
  {
    name: "Kalamazoo College",
    slug: "kalamazoo-college",
    location: "Kalamazoo, MI",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 1400,
    studentsAdmittedPercent: 70,
    costOfAttendanceInState: 67810,
    costOfAttendanceOutOfState: 67810,
    studentFacultyRatio: "13:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 87,
    graduationRate4yr: 73,
    graduationRate6yr: 80,
    medianEarnings10yr: 50000,
    website: "https://www.kzoo.edu",
    description: "Kalamazoo College is a private liberal arts college in Kalamazoo, Michigan. Founded in 1833, it is one of the oldest colleges in Michigan. K-College is known for its innovative K-Plan, which integrates academics, career development, civic engagement, and intercultural learning, including study abroad for nearly all students.",
    popularMajors: JSON.stringify(["Psychology", "Economics", "Biology", "Health Sciences", "Political Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 600, max: 700 }, math: { min: 580, max: 700 }, total: { min: 1180, max: 1400 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 25, max: 31 }, percentSubmitted: 45 }),
    totalApplicants: 4000,
    totalAdmitted: 2800,
    totalEnrolled: 390,
    yieldRate: 13.9,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 30000,
    genderDistribution: JSON.stringify({ women: 58, men: 42 }),
    raceEthnicity: JSON.stringify({ White: 66, Hispanic: 10, Asian: 7, Black: 6, "Two or More Races": 6, International: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Important"
    }),
    primaryColor: "#FF6600",
    secondaryColor: "#000000"
  },
  {
    name: "Hope College",
    slug: "hope-college",
    location: "Holland, MI",
    setting: "Small Town",
    institutionalSector: "Private",
    undergraduateEnrollment: 2800,
    studentsAdmittedPercent: 78,
    costOfAttendanceInState: 52840,
    costOfAttendanceOutOfState: 52840,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 86,
    graduationRate4yr: 68,
    graduationRate6yr: 78,
    medianEarnings10yr: 52000,
    website: "https://www.hope.edu",
    description: "Hope College is a private liberal arts college in Holland, Michigan. Founded in 1866, it is affiliated with the Reformed Church in America. Hope is known for its strong programs in sciences, particularly chemistry and engineering, as well as its commitment to undergraduate research and faith-based education.",
    popularMajors: JSON.stringify(["Biology", "Psychology", "Business", "Engineering", "Nursing"]),
    satScores: JSON.stringify({ readingWriting: { min: 550, max: 660 }, math: { min: 550, max: 670 }, total: { min: 1100, max: 1330 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 50 }),
    totalApplicants: 5500,
    totalAdmitted: 4290,
    totalEnrolled: 730,
    yieldRate: 17.0,
    rdDeadline: "Rolling",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 28000,
    genderDistribution: JSON.stringify({ women: 58, men: 42 }),
    raceEthnicity: JSON.stringify({ White: 80, Hispanic: 7, Asian: 4, Black: 3, "Two or More Races": 4, International: 2 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#002F6C",
    secondaryColor: "#FF8200"
  },
  {
    name: "DePauw University",
    slug: "depauw-university",
    location: "Greencastle, IN",
    setting: "Rural",
    institutionalSector: "Private",
    undergraduateEnrollment: 1800,
    studentsAdmittedPercent: 67,
    costOfAttendanceInState: 69880,
    costOfAttendanceOutOfState: 69880,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 86,
    graduationRate4yr: 75,
    graduationRate6yr: 81,
    medianEarnings10yr: 58000,
    website: "https://www.depauw.edu",
    description: "DePauw University is a private liberal arts university in Greencastle, Indiana. Founded in 1837, it has a strong tradition in journalism, music, and business. DePauw's Management Fellows and Media Fellows programs provide distinctive career preparation, and the university has produced numerous Fortune 500 executives.",
    popularMajors: JSON.stringify(["Economics", "Communication", "Biology", "Political Science", "English"]),
    satScores: JSON.stringify({ readingWriting: { min: 580, max: 680 }, math: { min: 570, max: 680 }, total: { min: 1150, max: 1360 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 25, max: 30 }, percentSubmitted: 45 }),
    totalApplicants: 5500,
    totalAdmitted: 3685,
    totalEnrolled: 520,
    yieldRate: 14.1,
    rdDeadline: "February 1",
    edDeadline: "November 15",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 34000,
    genderDistribution: JSON.stringify({ women: 53, men: 47 }),
    raceEthnicity: JSON.stringify({ White: 66, Hispanic: 9, Black: 7, International: 8, Asian: 5, "Two or More Races": 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Important"
    }),
    primaryColor: "#C49E17",
    secondaryColor: "#231F20"
  },

  // Additional Notable Universities
  {
    name: "Seton Hall University",
    slug: "seton-hall-university",
    location: "South Orange, NJ",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 6300,
    studentsAdmittedPercent: 74,
    costOfAttendanceInState: 67960,
    costOfAttendanceOutOfState: 67960,
    studentFacultyRatio: "14:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 86,
    graduationRate4yr: 63,
    graduationRate6yr: 73,
    medianEarnings10yr: 64000,
    website: "https://www.shu.edu",
    description: "Seton Hall University is a private Catholic university in South Orange, New Jersey. Founded in 1856, it is one of the oldest diocesan universities in the United States. Seton Hall is known for its strong programs in nursing, business, and diplomacy, and its proximity to New York City provides excellent career opportunities.",
    popularMajors: JSON.stringify(["Nursing", "Finance", "Biology", "Criminal Justice", "Communications"]),
    satScores: JSON.stringify({ readingWriting: { min: 570, max: 670 }, math: { min: 560, max: 670 }, total: { min: 1130, max: 1340 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 24, max: 30 }, percentSubmitted: 25 }),
    totalApplicants: 16000,
    totalAdmitted: 11840,
    totalEnrolled: 1450,
    yieldRate: 12.2,
    rdDeadline: "Rolling",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 36000,
    genderDistribution: JSON.stringify({ women: 57, men: 43 }),
    raceEthnicity: JSON.stringify({ White: 52, Hispanic: 18, Black: 12, Asian: 8, "Two or More Races": 5, International: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#004B87",
    secondaryColor: "#FFFFFF"
  },
  {
    name: "Quinnipiac University",
    slug: "quinnipiac-university",
    location: "Hamden, CT",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 7000,
    studentsAdmittedPercent: 78,
    costOfAttendanceInState: 69590,
    costOfAttendanceOutOfState: 69590,
    studentFacultyRatio: "12:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 87,
    graduationRate4yr: 73,
    graduationRate6yr: 79,
    medianEarnings10yr: 62000,
    website: "https://www.qu.edu",
    description: "Quinnipiac University is a private university in Hamden, Connecticut. Founded in 1929, it is known for its strong programs in health sciences, journalism, and business. The Quinnipiac Poll is nationally recognized for its public opinion research. The university has a modern campus with strong career placement.",
    popularMajors: JSON.stringify(["Nursing", "Physical Therapy", "Finance", "Communications", "Health Sciences"]),
    satScores: JSON.stringify({ readingWriting: { min: 570, max: 660 }, math: { min: 560, max: 660 }, total: { min: 1130, max: 1320 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 24, max: 29 }, percentSubmitted: 25 }),
    totalApplicants: 16000,
    totalAdmitted: 12480,
    totalEnrolled: 1800,
    yieldRate: 14.4,
    rdDeadline: "February 1",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 42000,
    genderDistribution: JSON.stringify({ women: 62, men: 38 }),
    raceEthnicity: JSON.stringify({ White: 72, Hispanic: 10, Asian: 5, Black: 5, "Two or More Races": 4, International: 4 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#002B5C",
    secondaryColor: "#CFB87C"
  }
];

async function main() {
  console.log("Adding new colleges to database - Batch 5...\n");

  let added = 0;
  let updated = 0;

  for (const college of newColleges) {
    const existing = await db.college.findUnique({
      where: { slug: college.slug },
    });

    if (existing) {
      // Update existing college with new data
      await db.college.update({
        where: { slug: college.slug },
        data: college,
      });
      console.log(`Updated: ${college.name}`);
      updated++;
    } else {
      // Add new college
      await db.college.create({
        data: college,
      });
      console.log(`Added: ${college.name}`);
      added++;
    }
  }

  const totalColleges = await db.college.count();
  console.log(`\n✓ Added ${added} new colleges`);
  console.log(`✓ Updated ${updated} existing colleges`);
  console.log(`Total colleges in database: ${totalColleges}`);

  await db.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
