/**
 * Add more notable colleges to the database - Batch 4
 * Focus on: Women's colleges, additional LACs, more regional universities
 * Data sourced from Common Data Set 2023-2024, IPEDS, and institutional websites
 */

import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

interface CollegeData {
  name: string;
  slug: string;
  location: string;
  setting: string;
  institutionalSector: string;
  undergraduateEnrollment: number;
  studentsAdmittedPercent: number;
  costOfAttendanceInState: number;
  costOfAttendanceOutOfState: number;
  studentFacultyRatio: string;
  admissionsSelectivity: string;
  testPolicy: string;
  retentionRate: number;
  graduationRate4yr: number;
  graduationRate6yr: number;
  medianEarnings10yr: number;
  website: string;
  description: string;
  popularMajors: string;
  satScores: string;
  actScores: string;
  totalApplicants: number;
  totalAdmitted: number;
  totalEnrolled: number;
  yieldRate: number;
  rdDeadline: string;
  eaDeadline?: string;
  edDeadline?: string;
  earlyActionType?: string;
  fafsaRequired: boolean;
  cssProfileRequired: boolean;
  averageNetPrice: number;
  genderDistribution: string;
  raceEthnicity: string;
  admissionConsiderations: string;
  primaryColor: string;
  secondaryColor?: string;
}

const newColleges: CollegeData[] = [
  // Women's Colleges (Seven Sisters and others)
  {
    name: "Bryn Mawr College",
    slug: "bryn-mawr-college",
    location: "Bryn Mawr, PA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 1400,
    studentsAdmittedPercent: 32,
    costOfAttendanceInState: 77640,
    costOfAttendanceOutOfState: 77640,
    studentFacultyRatio: "8:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 92,
    graduationRate4yr: 81,
    graduationRate6yr: 87,
    medianEarnings10yr: 58000,
    website: "https://www.brynmawr.edu",
    description: "Bryn Mawr College is a private women's liberal arts college in Bryn Mawr, Pennsylvania. Founded in 1885 as one of the Seven Sisters colleges, it is known for its rigorous academic programs and historic campus architecture. Bryn Mawr has a strong tradition in the sciences and humanities and participates in a tri-college consortium with Haverford and Swarthmore.",
    popularMajors: JSON.stringify(["Biology", "Political Science", "Psychology", "Economics", "English"]),
    satScores: JSON.stringify({ readingWriting: { min: 680, max: 750 }, math: { min: 660, max: 760 }, total: { min: 1340, max: 1510 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 30, max: 34 }, percentSubmitted: 25 }),
    totalApplicants: 4200,
    totalAdmitted: 1344,
    totalEnrolled: 360,
    yieldRate: 26.8,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 28000,
    genderDistribution: JSON.stringify({ women: 100, men: 0 }),
    raceEthnicity: JSON.stringify({ White: 40, Asian: 20, Hispanic: 12, Black: 6, "Two or More Races": 7, International: 15 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#003865"
  },
  {
    name: "Mount Holyoke College",
    slug: "mount-holyoke-college",
    location: "South Hadley, MA",
    setting: "Rural",
    institutionalSector: "Private",
    undergraduateEnrollment: 2100,
    studentsAdmittedPercent: 46,
    costOfAttendanceInState: 75770,
    costOfAttendanceOutOfState: 75770,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 88,
    graduationRate4yr: 77,
    graduationRate6yr: 85,
    medianEarnings10yr: 54000,
    website: "https://www.mtholyoke.edu",
    description: "Mount Holyoke College is a private women's liberal arts college in South Hadley, Massachusetts. Founded in 1837, it is the oldest of the Seven Sisters colleges and was the first institution of higher learning to award degrees to women. Mount Holyoke is known for its strong science programs and is part of the Five College Consortium.",
    popularMajors: JSON.stringify(["Biology", "Psychology", "Economics", "International Relations", "Computer Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 660, max: 740 }, math: { min: 640, max: 740 }, total: { min: 1300, max: 1480 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 29, max: 33 }, percentSubmitted: 20 }),
    totalApplicants: 5200,
    totalAdmitted: 2392,
    totalEnrolled: 550,
    yieldRate: 23.0,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 26000,
    genderDistribution: JSON.stringify({ women: 100, men: 0 }),
    raceEthnicity: JSON.stringify({ White: 42, Asian: 15, Hispanic: 11, Black: 6, "Two or More Races": 6, International: 20 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#003C71",
    secondaryColor: "#7BAFD4"
  },
  {
    name: "Scripps College",
    slug: "scripps-college",
    location: "Claremont, CA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 1080,
    studentsAdmittedPercent: 29,
    costOfAttendanceInState: 80640,
    costOfAttendanceOutOfState: 80640,
    studentFacultyRatio: "9:1",
    admissionsSelectivity: "Most Selective",
    testPolicy: "Test Optional",
    retentionRate: 93,
    graduationRate4yr: 84,
    graduationRate6yr: 90,
    medianEarnings10yr: 56000,
    website: "https://www.scrippscollege.edu",
    description: "Scripps College is a private women's liberal arts college in Claremont, California. Founded in 1926, it is a member of the Claremont Colleges consortium. Scripps is known for its beautiful Mediterranean-style campus, strong humanities programs, and emphasis on interdisciplinary learning. Students can cross-register at all five Claremont Colleges.",
    popularMajors: JSON.stringify(["Psychology", "Economics", "Biology", "Politics & International Relations", "Media Studies"]),
    satScores: JSON.stringify({ readingWriting: { min: 700, max: 760 }, math: { min: 680, max: 770 }, total: { min: 1380, max: 1530 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 31, max: 34 }, percentSubmitted: 25 }),
    totalApplicants: 4800,
    totalAdmitted: 1392,
    totalEnrolled: 280,
    yieldRate: 20.1,
    rdDeadline: "January 1",
    edDeadline: "November 1",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 32000,
    genderDistribution: JSON.stringify({ women: 100, men: 0 }),
    raceEthnicity: JSON.stringify({ White: 38, Asian: 18, Hispanic: 16, "Two or More Races": 10, Black: 5, International: 13 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#59733F",
    secondaryColor: "#8E6F3E"
  },
  {
    name: "Agnes Scott College",
    slug: "agnes-scott-college",
    location: "Decatur, GA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 950,
    studentsAdmittedPercent: 70,
    costOfAttendanceInState: 58000,
    costOfAttendanceOutOfState: 58000,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 82,
    graduationRate4yr: 62,
    graduationRate6yr: 70,
    medianEarnings10yr: 45000,
    website: "https://www.agnesscott.edu",
    description: "Agnes Scott College is a private women's liberal arts college in Decatur, Georgia, adjacent to Atlanta. Founded in 1889, it is known for its strong programs in the sciences, particularly its SUMMIT curriculum which guarantees every student a global learning experience. The college's Victorian Gothic campus is a National Historic Landmark.",
    popularMajors: JSON.stringify(["Psychology", "Biology", "Public Health", "Business Management", "Political Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 580, max: 680 }, math: { min: 540, max: 650 }, total: { min: 1120, max: 1330 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 24, max: 30 }, percentSubmitted: 30 }),
    totalApplicants: 2200,
    totalAdmitted: 1540,
    totalEnrolled: 280,
    yieldRate: 18.2,
    rdDeadline: "March 15",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 26000,
    genderDistribution: JSON.stringify({ women: 100, men: 0 }),
    raceEthnicity: JSON.stringify({ Black: 36, White: 30, Hispanic: 12, Asian: 8, "Two or More Races": 8, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#7E1416"
  },

  // More Liberal Arts Colleges
  {
    name: "Wheaton College (MA)",
    slug: "wheaton-college-ma",
    location: "Norton, MA",
    setting: "Rural",
    institutionalSector: "Private",
    undergraduateEnrollment: 1700,
    studentsAdmittedPercent: 66,
    costOfAttendanceInState: 72350,
    costOfAttendanceOutOfState: 72350,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 85,
    graduationRate4yr: 73,
    graduationRate6yr: 78,
    medianEarnings10yr: 52000,
    website: "https://www.wheatoncollege.edu",
    description: "Wheaton College is a private coeducational liberal arts college in Norton, Massachusetts. Founded in 1834 as a women's seminary, it became coeducational in 1988. Wheaton is known for its focus on experiential learning and connecting curriculum with career preparation, and its beautiful 400-acre campus.",
    popularMajors: JSON.stringify(["Psychology", "Business & Management", "Biology", "Economics", "Political Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 600, max: 690 }, math: { min: 580, max: 680 }, total: { min: 1180, max: 1370 }, percentSubmitted: 25 }),
    actScores: JSON.stringify({ composite: { min: 26, max: 31 }, percentSubmitted: 15 }),
    totalApplicants: 6500,
    totalAdmitted: 4290,
    totalEnrolled: 480,
    yieldRate: 11.2,
    rdDeadline: "January 15",
    edDeadline: "November 15",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 35000,
    genderDistribution: JSON.stringify({ women: 62, men: 38 }),
    raceEthnicity: JSON.stringify({ White: 58, Hispanic: 11, Black: 8, Asian: 6, "Two or More Races": 6, International: 11 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#003262",
    secondaryColor: "#E2B02C"
  },
  {
    name: "Furman University",
    slug: "furman-university",
    location: "Greenville, SC",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2900,
    studentsAdmittedPercent: 58,
    costOfAttendanceInState: 71424,
    costOfAttendanceOutOfState: 71424,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 89,
    graduationRate4yr: 77,
    graduationRate6yr: 84,
    medianEarnings10yr: 58000,
    website: "https://www.furman.edu",
    description: "Furman University is a private liberal arts university in Greenville, South Carolina. Founded in 1826, it is known for its beautiful 750-acre campus, strong pre-professional programs, and emphasis on engaged learning. Furman has consistently ranked among the top liberal arts universities in the South.",
    popularMajors: JSON.stringify(["Business Administration", "Political Science", "Biology", "Health Sciences", "Communication Studies"]),
    satScores: JSON.stringify({ readingWriting: { min: 620, max: 710 }, math: { min: 610, max: 710 }, total: { min: 1230, max: 1420 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 27, max: 32 }, percentSubmitted: 40 }),
    totalApplicants: 7000,
    totalAdmitted: 4060,
    totalEnrolled: 720,
    yieldRate: 17.7,
    rdDeadline: "January 15",
    edDeadline: "November 1",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 58, men: 42 }),
    raceEthnicity: JSON.stringify({ White: 74, Hispanic: 6, Black: 5, Asian: 5, "Two or More Races": 4, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#582C83"
  },
  {
    name: "Sewanee: The University of the South",
    slug: "sewanee-university-of-the-south",
    location: "Sewanee, TN",
    setting: "Rural",
    institutionalSector: "Private",
    undergraduateEnrollment: 1700,
    studentsAdmittedPercent: 54,
    costOfAttendanceInState: 67550,
    costOfAttendanceOutOfState: 67550,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 87,
    graduationRate4yr: 73,
    graduationRate6yr: 80,
    medianEarnings10yr: 50000,
    website: "https://www.sewanee.edu",
    description: "Sewanee: The University of the South is a private liberal arts college on the Cumberland Plateau in Tennessee. Founded in 1857 by the Episcopal Church, it is known for its stunning 13,000-acre campus ('The Domain'), academic traditions, and strong sense of community. Sewanee maintains unique traditions including an honor code and academic gowns.",
    popularMajors: JSON.stringify(["English", "Economics", "Biology", "Environmental Studies", "History"]),
    satScores: JSON.stringify({ readingWriting: { min: 610, max: 700 }, math: { min: 580, max: 680 }, total: { min: 1190, max: 1380 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 26, max: 31 }, percentSubmitted: 50 }),
    totalApplicants: 5500,
    totalAdmitted: 2970,
    totalEnrolled: 480,
    yieldRate: 16.2,
    rdDeadline: "February 1",
    edDeadline: "November 15",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 30000,
    genderDistribution: JSON.stringify({ women: 53, men: 47 }),
    raceEthnicity: JSON.stringify({ White: 80, Hispanic: 5, Black: 4, "Two or More Races": 4, Asian: 2, International: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#582C83"
  },
  {
    name: "Wofford College",
    slug: "wofford-college",
    location: "Spartanburg, SC",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 1800,
    studentsAdmittedPercent: 50,
    costOfAttendanceInState: 67130,
    costOfAttendanceOutOfState: 67130,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 87,
    graduationRate4yr: 77,
    graduationRate6yr: 82,
    medianEarnings10yr: 58000,
    website: "https://www.wofford.edu",
    description: "Wofford College is a private liberal arts college in Spartanburg, South Carolina. Founded in 1854, it is one of the oldest colleges in the South. Wofford is known for its strong programs in business, pre-med, and the sciences, and its emphasis on hands-on learning through research and internships.",
    popularMajors: JSON.stringify(["Business Economics", "Biology", "Finance", "Psychology", "Accounting"]),
    satScores: JSON.stringify({ readingWriting: { min: 600, max: 690 }, math: { min: 590, max: 690 }, total: { min: 1190, max: 1380 }, percentSubmitted: 50 }),
    actScores: JSON.stringify({ composite: { min: 26, max: 31 }, percentSubmitted: 45 }),
    totalApplicants: 4500,
    totalAdmitted: 2250,
    totalEnrolled: 480,
    yieldRate: 21.3,
    rdDeadline: "February 1",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 32000,
    genderDistribution: JSON.stringify({ women: 50, men: 50 }),
    raceEthnicity: JSON.stringify({ White: 79, Black: 7, Hispanic: 4, "Two or More Races": 4, Asian: 2, International: 4 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#886B2D"
  },
  {
    name: "Allegheny College",
    slug: "allegheny-college",
    location: "Meadville, PA",
    setting: "Small Town",
    institutionalSector: "Private",
    undergraduateEnrollment: 1650,
    studentsAdmittedPercent: 70,
    costOfAttendanceInState: 68160,
    costOfAttendanceOutOfState: 68160,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 82,
    graduationRate4yr: 68,
    graduationRate6yr: 76,
    medianEarnings10yr: 50000,
    website: "https://www.allegheny.edu",
    description: "Allegheny College is a private liberal arts college in Meadville, Pennsylvania. Founded in 1815, it is one of the oldest colleges in the United States. Allegheny is known for requiring students to complete a major and minor in different academic divisions, promoting interdisciplinary thinking and intellectual breadth.",
    popularMajors: JSON.stringify(["Biology", "Psychology", "Economics", "Environmental Science", "Political Science"]),
    satScores: JSON.stringify({ readingWriting: { min: 560, max: 660 }, math: { min: 550, max: 660 }, total: { min: 1110, max: 1320 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 24, max: 30 }, percentSubmitted: 35 }),
    totalApplicants: 5000,
    totalAdmitted: 3500,
    totalEnrolled: 480,
    yieldRate: 13.7,
    rdDeadline: "February 15",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 28000,
    genderDistribution: JSON.stringify({ women: 54, men: 46 }),
    raceEthnicity: JSON.stringify({ White: 72, Hispanic: 7, Black: 7, "Two or More Races": 5, Asian: 3, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#002855",
    secondaryColor: "#E8AA14"
  },
  {
    name: "Muhlenberg College",
    slug: "muhlenberg-college",
    location: "Allentown, PA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2200,
    studentsAdmittedPercent: 58,
    costOfAttendanceInState: 72970,
    costOfAttendanceOutOfState: 72970,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 88,
    graduationRate4yr: 78,
    graduationRate6yr: 84,
    medianEarnings10yr: 58000,
    website: "https://www.muhlenberg.edu",
    description: "Muhlenberg College is a private liberal arts college in Allentown, Pennsylvania. Founded in 1848 and affiliated with the Lutheran church, it is known for its strong pre-med and theatre programs. Muhlenberg emphasizes interdisciplinary learning and community engagement, with a beautiful 82-acre campus.",
    popularMajors: JSON.stringify(["Business Administration", "Psychology", "Biology", "Theatre", "Neuroscience"]),
    satScores: JSON.stringify({ readingWriting: { min: 600, max: 690 }, math: { min: 590, max: 690 }, total: { min: 1190, max: 1380 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 26, max: 31 }, percentSubmitted: 25 }),
    totalApplicants: 6200,
    totalAdmitted: 3596,
    totalEnrolled: 560,
    yieldRate: 15.6,
    rdDeadline: "February 15",
    edDeadline: "November 15",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 36000,
    genderDistribution: JSON.stringify({ women: 58, men: 42 }),
    raceEthnicity: JSON.stringify({ White: 72, Hispanic: 8, Black: 5, Asian: 4, "Two or More Races": 5, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#CC0033"
  },
  {
    name: "Ursinus College",
    slug: "ursinus-college",
    location: "Collegeville, PA",
    setting: "Suburban",
    institutionalSector: "Private",
    undergraduateEnrollment: 1200,
    studentsAdmittedPercent: 78,
    costOfAttendanceInState: 70370,
    costOfAttendanceOutOfState: 70370,
    studentFacultyRatio: "10:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 84,
    graduationRate4yr: 73,
    graduationRate6yr: 79,
    medianEarnings10yr: 54000,
    website: "https://www.ursinus.edu",
    description: "Ursinus College is a private liberal arts college in Collegeville, Pennsylvania. Founded in 1869, it is known for its strong science programs and commitment to undergraduate research. The college has a distinctive Common Intellectual Experience (CIE) curriculum that all students complete.",
    popularMajors: JSON.stringify(["Biology", "Business Economics", "Psychology", "Exercise & Sport Science", "Neuroscience"]),
    satScores: JSON.stringify({ readingWriting: { min: 560, max: 660 }, math: { min: 540, max: 650 }, total: { min: 1100, max: 1310 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 29 }, percentSubmitted: 25 }),
    totalApplicants: 3200,
    totalAdmitted: 2496,
    totalEnrolled: 340,
    yieldRate: 13.6,
    rdDeadline: "February 1",
    eaDeadline: "December 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 32000,
    genderDistribution: JSON.stringify({ women: 52, men: 48 }),
    raceEthnicity: JSON.stringify({ White: 68, Hispanic: 10, Black: 8, Asian: 4, "Two or More Races": 5, International: 5 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Very Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#C8102E"
  },
  {
    name: "Beloit College",
    slug: "beloit-college",
    location: "Beloit, WI",
    setting: "Small Town",
    institutionalSector: "Private",
    undergraduateEnrollment: 1100,
    studentsAdmittedPercent: 65,
    costOfAttendanceInState: 64990,
    costOfAttendanceOutOfState: 64990,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 82,
    graduationRate4yr: 66,
    graduationRate6yr: 75,
    medianEarnings10yr: 45000,
    website: "https://www.beloit.edu",
    description: "Beloit College is a private liberal arts college in Beloit, Wisconsin. Founded in 1846, it is known for its strong anthropology program and the Logan Museum of Anthropology on campus. Beloit emphasizes creative and critical thinking, with a focus on hands-on learning and student research.",
    popularMajors: JSON.stringify(["Anthropology", "Psychology", "Biology", "Creative Writing", "Economics"]),
    satScores: JSON.stringify({ readingWriting: { min: 560, max: 680 }, math: { min: 530, max: 660 }, total: { min: 1090, max: 1340 }, percentSubmitted: 30 }),
    actScores: JSON.stringify({ composite: { min: 23, max: 30 }, percentSubmitted: 35 }),
    totalApplicants: 2800,
    totalAdmitted: 1820,
    totalEnrolled: 290,
    yieldRate: 15.9,
    rdDeadline: "Rolling",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 28000,
    genderDistribution: JSON.stringify({ women: 56, men: 44 }),
    raceEthnicity: JSON.stringify({ White: 60, Hispanic: 12, Black: 6, Asian: 5, "Two or More Races": 6, International: 11 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#003865"
  },

  // Additional Regional/Comprehensive Universities
  {
    name: "Drake University",
    slug: "drake-university",
    location: "Des Moines, IA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 2900,
    studentsAdmittedPercent: 68,
    costOfAttendanceInState: 59220,
    costOfAttendanceOutOfState: 59220,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 87,
    graduationRate4yr: 70,
    graduationRate6yr: 79,
    medianEarnings10yr: 56000,
    website: "https://www.drake.edu",
    description: "Drake University is a private university in Des Moines, Iowa. Founded in 1881, it is known for its strong programs in pharmacy, actuarial science, journalism, and law. Drake's location in Iowa's capital provides excellent internship opportunities in government and business.",
    popularMajors: JSON.stringify(["Pharmacy", "Actuarial Science", "Marketing", "Journalism", "Psychology"]),
    satScores: JSON.stringify({ readingWriting: { min: 570, max: 680 }, math: { min: 560, max: 680 }, total: { min: 1130, max: 1360 }, percentSubmitted: 35 }),
    actScores: JSON.stringify({ composite: { min: 24, max: 30 }, percentSubmitted: 55 }),
    totalApplicants: 7500,
    totalAdmitted: 5100,
    totalEnrolled: 800,
    yieldRate: 15.7,
    rdDeadline: "March 1",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 28000,
    genderDistribution: JSON.stringify({ women: 59, men: 41 }),
    raceEthnicity: JSON.stringify({ White: 75, Hispanic: 6, Asian: 5, Black: 4, "Two or More Races": 4, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#004477",
    secondaryColor: "#FFFFFF"
  },
  {
    name: "Butler University",
    slug: "butler-university",
    location: "Indianapolis, IN",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 4600,
    studentsAdmittedPercent: 72,
    costOfAttendanceInState: 61440,
    costOfAttendanceOutOfState: 61440,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 88,
    graduationRate4yr: 70,
    graduationRate6yr: 79,
    medianEarnings10yr: 55000,
    website: "https://www.butler.edu",
    description: "Butler University is a private university in Indianapolis, Indiana. Founded in 1855, it is known for its strong programs in pharmacy, business, dance, and the performing arts. Butler's Division I basketball program and location in Indianapolis provide a vibrant campus atmosphere.",
    popularMajors: JSON.stringify(["Pharmacy", "Finance", "Marketing", "Biology", "Dance"]),
    satScores: JSON.stringify({ readingWriting: { min: 570, max: 670 }, math: { min: 560, max: 670 }, total: { min: 1130, max: 1340 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 25, max: 30 }, percentSubmitted: 50 }),
    totalApplicants: 15000,
    totalAdmitted: 10800,
    totalEnrolled: 1200,
    yieldRate: 11.1,
    rdDeadline: "February 1",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 35000,
    genderDistribution: JSON.stringify({ women: 60, men: 40 }),
    raceEthnicity: JSON.stringify({ White: 76, Hispanic: 6, Black: 4, Asian: 4, "Two or More Races": 4, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#13294B",
    secondaryColor: "#E5A823"
  },
  {
    name: "Creighton University",
    slug: "creighton-university",
    location: "Omaha, NE",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 4500,
    studentsAdmittedPercent: 78,
    costOfAttendanceInState: 61530,
    costOfAttendanceOutOfState: 61530,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 88,
    graduationRate4yr: 72,
    graduationRate6yr: 82,
    medianEarnings10yr: 62000,
    website: "https://www.creighton.edu",
    description: "Creighton University is a private Jesuit university in Omaha, Nebraska. Founded in 1878, it is known for its strong health sciences programs including medicine, dentistry, pharmacy, and nursing. Creighton emphasizes service and social justice in the Jesuit tradition.",
    popularMajors: JSON.stringify(["Nursing", "Biology", "Business Administration", "Psychology", "Health Sciences"]),
    satScores: JSON.stringify({ readingWriting: { min: 590, max: 690 }, math: { min: 580, max: 690 }, total: { min: 1170, max: 1380 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 25, max: 30 }, percentSubmitted: 55 }),
    totalApplicants: 12000,
    totalAdmitted: 9360,
    totalEnrolled: 1100,
    yieldRate: 11.8,
    rdDeadline: "February 15",
    eaDeadline: "November 1",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: false,
    averageNetPrice: 36000,
    genderDistribution: JSON.stringify({ women: 58, men: 42 }),
    raceEthnicity: JSON.stringify({ White: 71, Hispanic: 10, Asian: 7, Black: 3, "Two or More Races": 5, International: 4 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#004A8F",
    secondaryColor: "#FFFFFF"
  },
  {
    name: "University of San Diego",
    slug: "university-of-san-diego",
    location: "San Diego, CA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 6100,
    studentsAdmittedPercent: 53,
    costOfAttendanceInState: 75840,
    costOfAttendanceOutOfState: 75840,
    studentFacultyRatio: "14:1",
    admissionsSelectivity: "Very Selective",
    testPolicy: "Test Optional",
    retentionRate: 89,
    graduationRate4yr: 72,
    graduationRate6yr: 81,
    medianEarnings10yr: 66000,
    website: "https://www.sandiego.edu",
    description: "The University of San Diego is a private Catholic university overlooking Mission Bay and the Pacific Ocean. Founded in 1949, it is known for its beautiful Spanish Renaissance architecture, strong business and law programs, and idyllic San Diego location. USD emphasizes ethical leadership and social responsibility.",
    popularMajors: JSON.stringify(["Business Administration", "Finance", "Communications", "Psychology", "Biology"]),
    satScores: JSON.stringify({ readingWriting: { min: 620, max: 710 }, math: { min: 610, max: 710 }, total: { min: 1230, max: 1420 }, percentSubmitted: 40 }),
    actScores: JSON.stringify({ composite: { min: 27, max: 32 }, percentSubmitted: 30 }),
    totalApplicants: 18000,
    totalAdmitted: 9540,
    totalEnrolled: 1450,
    yieldRate: 15.2,
    rdDeadline: "January 15",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 44000,
    genderDistribution: JSON.stringify({ women: 55, men: 45 }),
    raceEthnicity: JSON.stringify({ White: 47, Hispanic: 22, Asian: 8, "Two or More Races": 8, Black: 3, International: 12 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Considered",
      "Character/personal qualities": "Important",
      "First generation": "Considered",
      "Interview": "Not Considered"
    }),
    primaryColor: "#002E5D",
    secondaryColor: "#A7BFD5"
  },
  {
    name: "Gonzaga University",
    slug: "gonzaga-university",
    location: "Spokane, WA",
    setting: "Urban",
    institutionalSector: "Private",
    undergraduateEnrollment: 5300,
    studentsAdmittedPercent: 70,
    costOfAttendanceInState: 67950,
    costOfAttendanceOutOfState: 67950,
    studentFacultyRatio: "11:1",
    admissionsSelectivity: "Selective",
    testPolicy: "Test Optional",
    retentionRate: 93,
    graduationRate4yr: 79,
    graduationRate6yr: 87,
    medianEarnings10yr: 62000,
    website: "https://www.gonzaga.edu",
    description: "Gonzaga University is a private Jesuit university in Spokane, Washington. Founded in 1887, it is known for its strong business, engineering, and nursing programs, as well as its nationally competitive men's basketball team. Gonzaga emphasizes the Jesuit values of cura personalis (care for the whole person) and service to others.",
    popularMajors: JSON.stringify(["Business Administration", "Nursing", "Mechanical Engineering", "Psychology", "Biology"]),
    satScores: JSON.stringify({ readingWriting: { min: 610, max: 700 }, math: { min: 600, max: 700 }, total: { min: 1210, max: 1400 }, percentSubmitted: 45 }),
    actScores: JSON.stringify({ composite: { min: 26, max: 31 }, percentSubmitted: 40 }),
    totalApplicants: 10000,
    totalAdmitted: 7000,
    totalEnrolled: 1350,
    yieldRate: 19.3,
    rdDeadline: "February 1",
    eaDeadline: "November 15",
    earlyActionType: "EA",
    fafsaRequired: true,
    cssProfileRequired: true,
    averageNetPrice: 38000,
    genderDistribution: JSON.stringify({ women: 53, men: 47 }),
    raceEthnicity: JSON.stringify({ White: 68, Hispanic: 11, Asian: 6, "Two or More Races": 7, Black: 2, International: 6 }),
    admissionConsiderations: JSON.stringify({
      "Rigor of secondary school record": "Very Important",
      "Academic GPA": "Very Important",
      "Standardized test scores": "Considered",
      "Application essay": "Very Important",
      "Recommendation(s)": "Important",
      "Extracurricular activities": "Important",
      "Talent/ability": "Important",
      "Character/personal qualities": "Very Important",
      "First generation": "Considered",
      "Interview": "Considered"
    }),
    primaryColor: "#002967",
    secondaryColor: "#C8102E"
  }
];

async function main() {
  console.log("Adding new colleges to database - Batch 4...\n");

  let added = 0;
  let updated = 0;

  for (const college of newColleges) {
    const existing = await db.college.findUnique({
      where: { slug: college.slug },
    });

    if (existing) {
      // Update existing college with new data
      await db.college.update({
        where: { slug: college.slug },
        data: college,
      });
      console.log(`Updated: ${college.name}`);
      updated++;
    } else {
      // Add new college
      await db.college.create({
        data: college,
      });
      console.log(`Added: ${college.name}`);
      added++;
    }
  }

  const totalColleges = await db.college.count();
  console.log(`\n✓ Added ${added} new colleges`);
  console.log(`✓ Updated ${updated} existing colleges`);
  console.log(`Total colleges in database: ${totalColleges}`);

  await db.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
